// Auto-generated. Do not edit!

// (in-package block_drawing_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class DrawingExecutionFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.current_face = null;
      this.current_waypoint = null;
      this.progress_fraction = null;
      this.estimated_force = null;
      this.state = null;
    }
    else {
      if (initObj.hasOwnProperty('current_face')) {
        this.current_face = initObj.current_face
      }
      else {
        this.current_face = 0;
      }
      if (initObj.hasOwnProperty('current_waypoint')) {
        this.current_waypoint = initObj.current_waypoint
      }
      else {
        this.current_waypoint = 0;
      }
      if (initObj.hasOwnProperty('progress_fraction')) {
        this.progress_fraction = initObj.progress_fraction
      }
      else {
        this.progress_fraction = 0.0;
      }
      if (initObj.hasOwnProperty('estimated_force')) {
        this.estimated_force = initObj.estimated_force
      }
      else {
        this.estimated_force = 0.0;
      }
      if (initObj.hasOwnProperty('state')) {
        this.state = initObj.state
      }
      else {
        this.state = '';
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type DrawingExecutionFeedback
    // Serialize message field [current_face]
    bufferOffset = _serializer.int32(obj.current_face, buffer, bufferOffset);
    // Serialize message field [current_waypoint]
    bufferOffset = _serializer.int32(obj.current_waypoint, buffer, bufferOffset);
    // Serialize message field [progress_fraction]
    bufferOffset = _serializer.float64(obj.progress_fraction, buffer, bufferOffset);
    // Serialize message field [estimated_force]
    bufferOffset = _serializer.float64(obj.estimated_force, buffer, bufferOffset);
    // Serialize message field [state]
    bufferOffset = _serializer.string(obj.state, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type DrawingExecutionFeedback
    let len;
    let data = new DrawingExecutionFeedback(null);
    // Deserialize message field [current_face]
    data.current_face = _deserializer.int32(buffer, bufferOffset);
    // Deserialize message field [current_waypoint]
    data.current_waypoint = _deserializer.int32(buffer, bufferOffset);
    // Deserialize message field [progress_fraction]
    data.progress_fraction = _deserializer.float64(buffer, bufferOffset);
    // Deserialize message field [estimated_force]
    data.estimated_force = _deserializer.float64(buffer, bufferOffset);
    // Deserialize message field [state]
    data.state = _deserializer.string(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += _getByteLength(object.state);
    return length + 28;
  }

  static datatype() {
    // Returns string type for a message object
    return 'block_drawing_msgs/DrawingExecutionFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '17f64e75c596ccac5812e834eece6216';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Feedback
    int32   current_face        # 当前正在画的面 (0~4)
    int32   current_waypoint    # 当前 waypoint 索引
    float64 progress_fraction   # 完成比例 [0.0, 1.0]
    float64 estimated_force     # 当前估计接触力 [N]
    string  state               # 执行器状态字符串
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new DrawingExecutionFeedback(null);
    if (msg.current_face !== undefined) {
      resolved.current_face = msg.current_face;
    }
    else {
      resolved.current_face = 0
    }

    if (msg.current_waypoint !== undefined) {
      resolved.current_waypoint = msg.current_waypoint;
    }
    else {
      resolved.current_waypoint = 0
    }

    if (msg.progress_fraction !== undefined) {
      resolved.progress_fraction = msg.progress_fraction;
    }
    else {
      resolved.progress_fraction = 0.0
    }

    if (msg.estimated_force !== undefined) {
      resolved.estimated_force = msg.estimated_force;
    }
    else {
      resolved.estimated_force = 0.0
    }

    if (msg.state !== undefined) {
      resolved.state = msg.state;
    }
    else {
      resolved.state = ''
    }

    return resolved;
    }
};

module.exports = DrawingExecutionFeedback;
