(cl:defpackage block_drawing_msgs-srv
  (:use )
  (:export
   "EXECUTEDRAWING"
   "<EXECUTEDRAWING-REQUEST>"
   "EXECUTEDRAWING-REQUEST"
   "<EXECUTEDRAWING-RESPONSE>"
   "EXECUTEDRAWING-RESPONSE"
   "GENERATETRAJECTORY"
   "<GENERATETRAJECTORY-REQUEST>"
   "GENERATETRAJECTORY-REQUEST"
   "<GENERATETRAJECTORY-RESPONSE>"
   "GENERATETRAJECTORY-RESPONSE"
   "SETBLOCKPOSE"
   "<SETBLOCKPOSE-REQUEST>"
   "SETBLOCKPOSE-REQUEST"
   "<SETBLOCKPOSE-RESPONSE>"
   "SETBLOCKPOSE-RESPONSE"
  ))

