// Generated by gencpp from file block_drawing_msgs/ContactState.msg
// DO NOT EDIT!


#ifndef BLOCK_DRAWING_MSGS_MESSAGE_CONTACTSTATE_H
#define BLOCK_DRAWING_MSGS_MESSAGE_CONTACTSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace block_drawing_msgs
{
template <class ContainerAllocator>
struct ContactState_
{
  typedef ContactState_<ContainerAllocator> Type;

  ContactState_()
    : normal_force(0.0)
    , torque_x(0.0)
    , torque_y(0.0)
    , torque_z(0.0)
    , in_contact(false)  {
    }
  ContactState_(const ContainerAllocator& _alloc)
    : normal_force(0.0)
    , torque_x(0.0)
    , torque_y(0.0)
    , torque_z(0.0)
    , in_contact(false)  {
  (void)_alloc;
    }



   typedef double _normal_force_type;
  _normal_force_type normal_force;

   typedef double _torque_x_type;
  _torque_x_type torque_x;

   typedef double _torque_y_type;
  _torque_y_type torque_y;

   typedef double _torque_z_type;
  _torque_z_type torque_z;

   typedef uint8_t _in_contact_type;
  _in_contact_type in_contact;





  typedef boost::shared_ptr< ::block_drawing_msgs::ContactState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::block_drawing_msgs::ContactState_<ContainerAllocator> const> ConstPtr;

}; // struct ContactState_

typedef ::block_drawing_msgs::ContactState_<std::allocator<void> > ContactState;

typedef boost::shared_ptr< ::block_drawing_msgs::ContactState > ContactStatePtr;
typedef boost::shared_ptr< ::block_drawing_msgs::ContactState const> ContactStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::block_drawing_msgs::ContactState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::block_drawing_msgs::ContactState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::block_drawing_msgs::ContactState_<ContainerAllocator1> & lhs, const ::block_drawing_msgs::ContactState_<ContainerAllocator2> & rhs)
{
  return lhs.normal_force == rhs.normal_force &&
    lhs.torque_x == rhs.torque_x &&
    lhs.torque_y == rhs.torque_y &&
    lhs.torque_z == rhs.torque_z &&
    lhs.in_contact == rhs.in_contact;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::block_drawing_msgs::ContactState_<ContainerAllocator1> & lhs, const ::block_drawing_msgs::ContactState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace block_drawing_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::block_drawing_msgs::ContactState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::block_drawing_msgs::ContactState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::block_drawing_msgs::ContactState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::block_drawing_msgs::ContactState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::block_drawing_msgs::ContactState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::block_drawing_msgs::ContactState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::block_drawing_msgs::ContactState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d94143f44062f49290d19adbd3e1fb22";
  }

  static const char* value(const ::block_drawing_msgs::ContactState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd94143f44062f492ULL;
  static const uint64_t static_value2 = 0x90d19adbd3e1fb22ULL;
};

template<class ContainerAllocator>
struct DataType< ::block_drawing_msgs::ContactState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "block_drawing_msgs/ContactState";
  }

  static const char* value(const ::block_drawing_msgs::ContactState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::block_drawing_msgs::ContactState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ContactState.msg\n"
"# 接触状态: 笔尖与物块表面的接触信息\n"
"\n"
"float64 normal_force        # 法向力估计值 [N]\n"
"float64 torque_x            # 末端力矩 X [Nm]\n"
"float64 torque_y            # 末端力矩 Y [Nm]\n"
"float64 torque_z            # 末端力矩 Z [Nm]\n"
"bool    in_contact          # 是否判定为接触中\n"
;
  }

  static const char* value(const ::block_drawing_msgs::ContactState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::block_drawing_msgs::ContactState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.normal_force);
      stream.next(m.torque_x);
      stream.next(m.torque_y);
      stream.next(m.torque_z);
      stream.next(m.in_contact);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ContactState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::block_drawing_msgs::ContactState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::block_drawing_msgs::ContactState_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "normal_force: ";
    Printer<double>::stream(s, indent + "  ", v.normal_force);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "torque_x: ";
    Printer<double>::stream(s, indent + "  ", v.torque_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "torque_y: ";
    Printer<double>::stream(s, indent + "  ", v.torque_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "torque_z: ";
    Printer<double>::stream(s, indent + "  ", v.torque_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "in_contact: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.in_contact);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BLOCK_DRAWING_MSGS_MESSAGE_CONTACTSTATE_H
