// Generated by gencpp from file block_drawing_msgs/DrawingExecutionFeedback.msg
// DO NOT EDIT!


#ifndef BLOCK_DRAWING_MSGS_MESSAGE_DRAWINGEXECUTIONFEEDBACK_H
#define BLOCK_DRAWING_MSGS_MESSAGE_DRAWINGEXECUTIONFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace block_drawing_msgs
{
template <class ContainerAllocator>
struct DrawingExecutionFeedback_
{
  typedef DrawingExecutionFeedback_<ContainerAllocator> Type;

  DrawingExecutionFeedback_()
    : current_face(0)
    , current_waypoint(0)
    , progress_fraction(0.0)
    , estimated_force(0.0)
    , state()  {
    }
  DrawingExecutionFeedback_(const ContainerAllocator& _alloc)
    : current_face(0)
    , current_waypoint(0)
    , progress_fraction(0.0)
    , estimated_force(0.0)
    , state(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _current_face_type;
  _current_face_type current_face;

   typedef int32_t _current_waypoint_type;
  _current_waypoint_type current_waypoint;

   typedef double _progress_fraction_type;
  _progress_fraction_type progress_fraction;

   typedef double _estimated_force_type;
  _estimated_force_type estimated_force;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::block_drawing_msgs::DrawingExecutionFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::block_drawing_msgs::DrawingExecutionFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct DrawingExecutionFeedback_

typedef ::block_drawing_msgs::DrawingExecutionFeedback_<std::allocator<void> > DrawingExecutionFeedback;

typedef boost::shared_ptr< ::block_drawing_msgs::DrawingExecutionFeedback > DrawingExecutionFeedbackPtr;
typedef boost::shared_ptr< ::block_drawing_msgs::DrawingExecutionFeedback const> DrawingExecutionFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::block_drawing_msgs::DrawingExecutionFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::block_drawing_msgs::DrawingExecutionFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::block_drawing_msgs::DrawingExecutionFeedback_<ContainerAllocator1> & lhs, const ::block_drawing_msgs::DrawingExecutionFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.current_face == rhs.current_face &&
    lhs.current_waypoint == rhs.current_waypoint &&
    lhs.progress_fraction == rhs.progress_fraction &&
    lhs.estimated_force == rhs.estimated_force &&
    lhs.state == rhs.state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::block_drawing_msgs::DrawingExecutionFeedback_<ContainerAllocator1> & lhs, const ::block_drawing_msgs::DrawingExecutionFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace block_drawing_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::block_drawing_msgs::DrawingExecutionFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::block_drawing_msgs::DrawingExecutionFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::block_drawing_msgs::DrawingExecutionFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::block_drawing_msgs::DrawingExecutionFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::block_drawing_msgs::DrawingExecutionFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::block_drawing_msgs::DrawingExecutionFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::block_drawing_msgs::DrawingExecutionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "17f64e75c596ccac5812e834eece6216";
  }

  static const char* value(const ::block_drawing_msgs::DrawingExecutionFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x17f64e75c596ccacULL;
  static const uint64_t static_value2 = 0x5812e834eece6216ULL;
};

template<class ContainerAllocator>
struct DataType< ::block_drawing_msgs::DrawingExecutionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "block_drawing_msgs/DrawingExecutionFeedback";
  }

  static const char* value(const ::block_drawing_msgs::DrawingExecutionFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::block_drawing_msgs::DrawingExecutionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Feedback\n"
"int32   current_face        # 当前正在画的面 (0~4)\n"
"int32   current_waypoint    # 当前 waypoint 索引\n"
"float64 progress_fraction   # 完成比例 [0.0, 1.0]\n"
"float64 estimated_force     # 当前估计接触力 [N]\n"
"string  state               # 执行器状态字符串\n"
"\n"
;
  }

  static const char* value(const ::block_drawing_msgs::DrawingExecutionFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::block_drawing_msgs::DrawingExecutionFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.current_face);
      stream.next(m.current_waypoint);
      stream.next(m.progress_fraction);
      stream.next(m.estimated_force);
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DrawingExecutionFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::block_drawing_msgs::DrawingExecutionFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::block_drawing_msgs::DrawingExecutionFeedback_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "current_face: ";
    Printer<int32_t>::stream(s, indent + "  ", v.current_face);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "current_waypoint: ";
    Printer<int32_t>::stream(s, indent + "  ", v.current_waypoint);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "progress_fraction: ";
    Printer<double>::stream(s, indent + "  ", v.progress_fraction);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "estimated_force: ";
    Printer<double>::stream(s, indent + "  ", v.estimated_force);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "state: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BLOCK_DRAWING_MSGS_MESSAGE_DRAWINGEXECUTIONFEEDBACK_H
