// Generated by gencpp from file block_drawing_msgs/DrawingExecutionAction.msg
// DO NOT EDIT!


#ifndef BLOCK_DRAWING_MSGS_MESSAGE_DRAWINGEXECUTIONACTION_H
#define BLOCK_DRAWING_MSGS_MESSAGE_DRAWINGEXECUTIONACTION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <block_drawing_msgs/DrawingExecutionActionGoal.h>
#include <block_drawing_msgs/DrawingExecutionActionResult.h>
#include <block_drawing_msgs/DrawingExecutionActionFeedback.h>

namespace block_drawing_msgs
{
template <class ContainerAllocator>
struct DrawingExecutionAction_
{
  typedef DrawingExecutionAction_<ContainerAllocator> Type;

  DrawingExecutionAction_()
    : action_goal()
    , action_result()
    , action_feedback()  {
    }
  DrawingExecutionAction_(const ContainerAllocator& _alloc)
    : action_goal(_alloc)
    , action_result(_alloc)
    , action_feedback(_alloc)  {
  (void)_alloc;
    }



   typedef  ::block_drawing_msgs::DrawingExecutionActionGoal_<ContainerAllocator>  _action_goal_type;
  _action_goal_type action_goal;

   typedef  ::block_drawing_msgs::DrawingExecutionActionResult_<ContainerAllocator>  _action_result_type;
  _action_result_type action_result;

   typedef  ::block_drawing_msgs::DrawingExecutionActionFeedback_<ContainerAllocator>  _action_feedback_type;
  _action_feedback_type action_feedback;





  typedef boost::shared_ptr< ::block_drawing_msgs::DrawingExecutionAction_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::block_drawing_msgs::DrawingExecutionAction_<ContainerAllocator> const> ConstPtr;

}; // struct DrawingExecutionAction_

typedef ::block_drawing_msgs::DrawingExecutionAction_<std::allocator<void> > DrawingExecutionAction;

typedef boost::shared_ptr< ::block_drawing_msgs::DrawingExecutionAction > DrawingExecutionActionPtr;
typedef boost::shared_ptr< ::block_drawing_msgs::DrawingExecutionAction const> DrawingExecutionActionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::block_drawing_msgs::DrawingExecutionAction_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::block_drawing_msgs::DrawingExecutionAction_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::block_drawing_msgs::DrawingExecutionAction_<ContainerAllocator1> & lhs, const ::block_drawing_msgs::DrawingExecutionAction_<ContainerAllocator2> & rhs)
{
  return lhs.action_goal == rhs.action_goal &&
    lhs.action_result == rhs.action_result &&
    lhs.action_feedback == rhs.action_feedback;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::block_drawing_msgs::DrawingExecutionAction_<ContainerAllocator1> & lhs, const ::block_drawing_msgs::DrawingExecutionAction_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace block_drawing_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::block_drawing_msgs::DrawingExecutionAction_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::block_drawing_msgs::DrawingExecutionAction_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::block_drawing_msgs::DrawingExecutionAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::block_drawing_msgs::DrawingExecutionAction_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::block_drawing_msgs::DrawingExecutionAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::block_drawing_msgs::DrawingExecutionAction_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::block_drawing_msgs::DrawingExecutionAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9ed779d0739eb25a29c24b6e506e1b8e";
  }

  static const char* value(const ::block_drawing_msgs::DrawingExecutionAction_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9ed779d0739eb25aULL;
  static const uint64_t static_value2 = 0x29c24b6e506e1b8eULL;
};

template<class ContainerAllocator>
struct DataType< ::block_drawing_msgs::DrawingExecutionAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "block_drawing_msgs/DrawingExecutionAction";
  }

  static const char* value(const ::block_drawing_msgs::DrawingExecutionAction_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::block_drawing_msgs::DrawingExecutionAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"DrawingExecutionActionGoal action_goal\n"
"DrawingExecutionActionResult action_result\n"
"DrawingExecutionActionFeedback action_feedback\n"
"\n"
"================================================================================\n"
"MSG: block_drawing_msgs/DrawingExecutionActionGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"DrawingExecutionGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: block_drawing_msgs/DrawingExecutionGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# DrawingExecution.action\n"
"# 绘画执行 Action: 可暂停/取消/反馈进度\n"
"\n"
"block_drawing_msgs/SurfaceTrajectory[] trajectories  # Goal: 要执行的轨迹序列\n"
"\n"
"================================================================================\n"
"MSG: block_drawing_msgs/SurfaceTrajectory\n"
"# SurfaceTrajectory.msg\n"
"# 单面轨迹: 包含该面所有 waypoints\n"
"\n"
"int32   face_id                    # 0=顶面, 1=前面, 2=右面, 3=后面, 4=左面\n"
"geometry_msgs/Pose[] waypoints     # 末端期望位姿 (含法兰补偿)\n"
"float64[] arc_lengths              # 累计弧长, 用于速度规划 [m]\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: block_drawing_msgs/DrawingExecutionActionResult\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalStatus status\n"
"DrawingExecutionResult result\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalStatus\n"
"GoalID goal_id\n"
"uint8 status\n"
"uint8 PENDING         = 0   # The goal has yet to be processed by the action server\n"
"uint8 ACTIVE          = 1   # The goal is currently being processed by the action server\n"
"uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing\n"
"                            #   and has since completed its execution (Terminal State)\n"
"uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)\n"
"uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due\n"
"                            #    to some failure (Terminal State)\n"
"uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,\n"
"                            #    because the goal was unattainable or invalid (Terminal State)\n"
"uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing\n"
"                            #    and has not yet completed execution\n"
"uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,\n"
"                            #    but the action server has not yet confirmed that the goal is canceled\n"
"uint8 RECALLED        = 8   # The goal received a cancel request before it started executing\n"
"                            #    and was successfully cancelled (Terminal State)\n"
"uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be\n"
"                            #    sent over the wire by an action server\n"
"\n"
"#Allow for the user to associate a string with GoalStatus for debugging\n"
"string text\n"
"\n"
"\n"
"================================================================================\n"
"MSG: block_drawing_msgs/DrawingExecutionResult\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Result\n"
"bool    completed           # 是否全部完成\n"
"int32   faces_drawn         # 已完成的面数\n"
"float64 total_arc_length    # 总弧长 [m]\n"
"string  message             # 错误信息 (如有)\n"
"\n"
"\n"
"================================================================================\n"
"MSG: block_drawing_msgs/DrawingExecutionActionFeedback\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalStatus status\n"
"DrawingExecutionFeedback feedback\n"
"\n"
"================================================================================\n"
"MSG: block_drawing_msgs/DrawingExecutionFeedback\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Feedback\n"
"int32   current_face        # 当前正在画的面 (0~4)\n"
"int32   current_waypoint    # 当前 waypoint 索引\n"
"float64 progress_fraction   # 完成比例 [0.0, 1.0]\n"
"float64 estimated_force     # 当前估计接触力 [N]\n"
"string  state               # 执行器状态字符串\n"
"\n"
;
  }

  static const char* value(const ::block_drawing_msgs::DrawingExecutionAction_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::block_drawing_msgs::DrawingExecutionAction_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action_goal);
      stream.next(m.action_result);
      stream.next(m.action_feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DrawingExecutionAction_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::block_drawing_msgs::DrawingExecutionAction_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::block_drawing_msgs::DrawingExecutionAction_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "action_goal: ";
    Printer< ::block_drawing_msgs::DrawingExecutionActionGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.action_goal);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "action_result: ";
    Printer< ::block_drawing_msgs::DrawingExecutionActionResult_<ContainerAllocator> >::stream(s, indent + "  ", v.action_result);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "action_feedback: ";
    Printer< ::block_drawing_msgs::DrawingExecutionActionFeedback_<ContainerAllocator> >::stream(s, indent + "  ", v.action_feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BLOCK_DRAWING_MSGS_MESSAGE_DRAWINGEXECUTIONACTION_H
