// Generated by gencpp from file block_drawing_msgs/DrawingExecutionGoal.msg
// DO NOT EDIT!


#ifndef BLOCK_DRAWING_MSGS_MESSAGE_DRAWINGEXECUTIONGOAL_H
#define BLOCK_DRAWING_MSGS_MESSAGE_DRAWINGEXECUTIONGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <block_drawing_msgs/SurfaceTrajectory.h>

namespace block_drawing_msgs
{
template <class ContainerAllocator>
struct DrawingExecutionGoal_
{
  typedef DrawingExecutionGoal_<ContainerAllocator> Type;

  DrawingExecutionGoal_()
    : trajectories()  {
    }
  DrawingExecutionGoal_(const ContainerAllocator& _alloc)
    : trajectories(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::block_drawing_msgs::SurfaceTrajectory_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::block_drawing_msgs::SurfaceTrajectory_<ContainerAllocator> >> _trajectories_type;
  _trajectories_type trajectories;





  typedef boost::shared_ptr< ::block_drawing_msgs::DrawingExecutionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::block_drawing_msgs::DrawingExecutionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct DrawingExecutionGoal_

typedef ::block_drawing_msgs::DrawingExecutionGoal_<std::allocator<void> > DrawingExecutionGoal;

typedef boost::shared_ptr< ::block_drawing_msgs::DrawingExecutionGoal > DrawingExecutionGoalPtr;
typedef boost::shared_ptr< ::block_drawing_msgs::DrawingExecutionGoal const> DrawingExecutionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::block_drawing_msgs::DrawingExecutionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::block_drawing_msgs::DrawingExecutionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::block_drawing_msgs::DrawingExecutionGoal_<ContainerAllocator1> & lhs, const ::block_drawing_msgs::DrawingExecutionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.trajectories == rhs.trajectories;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::block_drawing_msgs::DrawingExecutionGoal_<ContainerAllocator1> & lhs, const ::block_drawing_msgs::DrawingExecutionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace block_drawing_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::block_drawing_msgs::DrawingExecutionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::block_drawing_msgs::DrawingExecutionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::block_drawing_msgs::DrawingExecutionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::block_drawing_msgs::DrawingExecutionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::block_drawing_msgs::DrawingExecutionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::block_drawing_msgs::DrawingExecutionGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::block_drawing_msgs::DrawingExecutionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "18d4389c20600c83dad09467144e805f";
  }

  static const char* value(const ::block_drawing_msgs::DrawingExecutionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x18d4389c20600c83ULL;
  static const uint64_t static_value2 = 0xdad09467144e805fULL;
};

template<class ContainerAllocator>
struct DataType< ::block_drawing_msgs::DrawingExecutionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "block_drawing_msgs/DrawingExecutionGoal";
  }

  static const char* value(const ::block_drawing_msgs::DrawingExecutionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::block_drawing_msgs::DrawingExecutionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# DrawingExecution.action\n"
"# 绘画执行 Action: 可暂停/取消/反馈进度\n"
"\n"
"block_drawing_msgs/SurfaceTrajectory[] trajectories  # Goal: 要执行的轨迹序列\n"
"\n"
"================================================================================\n"
"MSG: block_drawing_msgs/SurfaceTrajectory\n"
"# SurfaceTrajectory.msg\n"
"# 单面轨迹: 包含该面所有 waypoints\n"
"\n"
"int32   face_id                    # 0=顶面, 1=前面, 2=右面, 3=后面, 4=左面\n"
"geometry_msgs/Pose[] waypoints     # 末端期望位姿 (含法兰补偿)\n"
"float64[] arc_lengths              # 累计弧长, 用于速度规划 [m]\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::block_drawing_msgs::DrawingExecutionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::block_drawing_msgs::DrawingExecutionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.trajectories);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DrawingExecutionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::block_drawing_msgs::DrawingExecutionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::block_drawing_msgs::DrawingExecutionGoal_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "trajectories: ";
    if (v.trajectories.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.trajectories.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::block_drawing_msgs::SurfaceTrajectory_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.trajectories[i]);
    }
    if (v.trajectories.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // BLOCK_DRAWING_MSGS_MESSAGE_DRAWINGEXECUTIONGOAL_H
