// Generated by gencpp from file block_drawing_msgs/DrawingExecutionResult.msg
// DO NOT EDIT!


#ifndef BLOCK_DRAWING_MSGS_MESSAGE_DRAWINGEXECUTIONRESULT_H
#define BLOCK_DRAWING_MSGS_MESSAGE_DRAWINGEXECUTIONRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace block_drawing_msgs
{
template <class ContainerAllocator>
struct DrawingExecutionResult_
{
  typedef DrawingExecutionResult_<ContainerAllocator> Type;

  DrawingExecutionResult_()
    : completed(false)
    , faces_drawn(0)
    , total_arc_length(0.0)
    , message()  {
    }
  DrawingExecutionResult_(const ContainerAllocator& _alloc)
    : completed(false)
    , faces_drawn(0)
    , total_arc_length(0.0)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _completed_type;
  _completed_type completed;

   typedef int32_t _faces_drawn_type;
  _faces_drawn_type faces_drawn;

   typedef double _total_arc_length_type;
  _total_arc_length_type total_arc_length;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::block_drawing_msgs::DrawingExecutionResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::block_drawing_msgs::DrawingExecutionResult_<ContainerAllocator> const> ConstPtr;

}; // struct DrawingExecutionResult_

typedef ::block_drawing_msgs::DrawingExecutionResult_<std::allocator<void> > DrawingExecutionResult;

typedef boost::shared_ptr< ::block_drawing_msgs::DrawingExecutionResult > DrawingExecutionResultPtr;
typedef boost::shared_ptr< ::block_drawing_msgs::DrawingExecutionResult const> DrawingExecutionResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::block_drawing_msgs::DrawingExecutionResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::block_drawing_msgs::DrawingExecutionResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::block_drawing_msgs::DrawingExecutionResult_<ContainerAllocator1> & lhs, const ::block_drawing_msgs::DrawingExecutionResult_<ContainerAllocator2> & rhs)
{
  return lhs.completed == rhs.completed &&
    lhs.faces_drawn == rhs.faces_drawn &&
    lhs.total_arc_length == rhs.total_arc_length &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::block_drawing_msgs::DrawingExecutionResult_<ContainerAllocator1> & lhs, const ::block_drawing_msgs::DrawingExecutionResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace block_drawing_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::block_drawing_msgs::DrawingExecutionResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::block_drawing_msgs::DrawingExecutionResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::block_drawing_msgs::DrawingExecutionResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::block_drawing_msgs::DrawingExecutionResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::block_drawing_msgs::DrawingExecutionResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::block_drawing_msgs::DrawingExecutionResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::block_drawing_msgs::DrawingExecutionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "97fbbf989dd52a803d908804451ece8a";
  }

  static const char* value(const ::block_drawing_msgs::DrawingExecutionResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x97fbbf989dd52a80ULL;
  static const uint64_t static_value2 = 0x3d908804451ece8aULL;
};

template<class ContainerAllocator>
struct DataType< ::block_drawing_msgs::DrawingExecutionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "block_drawing_msgs/DrawingExecutionResult";
  }

  static const char* value(const ::block_drawing_msgs::DrawingExecutionResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::block_drawing_msgs::DrawingExecutionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Result\n"
"bool    completed           # 是否全部完成\n"
"int32   faces_drawn         # 已完成的面数\n"
"float64 total_arc_length    # 总弧长 [m]\n"
"string  message             # 错误信息 (如有)\n"
"\n"
;
  }

  static const char* value(const ::block_drawing_msgs::DrawingExecutionResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::block_drawing_msgs::DrawingExecutionResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.completed);
      stream.next(m.faces_drawn);
      stream.next(m.total_arc_length);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DrawingExecutionResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::block_drawing_msgs::DrawingExecutionResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::block_drawing_msgs::DrawingExecutionResult_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "completed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.completed);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "faces_drawn: ";
    Printer<int32_t>::stream(s, indent + "  ", v.faces_drawn);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "total_arc_length: ";
    Printer<double>::stream(s, indent + "  ", v.total_arc_length);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BLOCK_DRAWING_MSGS_MESSAGE_DRAWINGEXECUTIONRESULT_H
