// Generated by gencpp from file block_drawing_msgs/GenerateTrajectory.msg
// DO NOT EDIT!


#ifndef BLOCK_DRAWING_MSGS_MESSAGE_GENERATETRAJECTORY_H
#define BLOCK_DRAWING_MSGS_MESSAGE_GENERATETRAJECTORY_H

#include <ros/service_traits.h>


#include <block_drawing_msgs/GenerateTrajectoryRequest.h>
#include <block_drawing_msgs/GenerateTrajectoryResponse.h>


namespace block_drawing_msgs
{

struct GenerateTrajectory
{

typedef GenerateTrajectoryRequest Request;
typedef GenerateTrajectoryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GenerateTrajectory
} // namespace block_drawing_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::block_drawing_msgs::GenerateTrajectory > {
  static const char* value()
  {
    return "8fbb008b13b5fc9766400a28fbedf619";
  }

  static const char* value(const ::block_drawing_msgs::GenerateTrajectory&) { return value(); }
};

template<>
struct DataType< ::block_drawing_msgs::GenerateTrajectory > {
  static const char* value()
  {
    return "block_drawing_msgs/GenerateTrajectory";
  }

  static const char* value(const ::block_drawing_msgs::GenerateTrajectory&) { return value(); }
};


// service_traits::MD5Sum< ::block_drawing_msgs::GenerateTrajectoryRequest> should match
// service_traits::MD5Sum< ::block_drawing_msgs::GenerateTrajectory >
template<>
struct MD5Sum< ::block_drawing_msgs::GenerateTrajectoryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::block_drawing_msgs::GenerateTrajectory >::value();
  }
  static const char* value(const ::block_drawing_msgs::GenerateTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::block_drawing_msgs::GenerateTrajectoryRequest> should match
// service_traits::DataType< ::block_drawing_msgs::GenerateTrajectory >
template<>
struct DataType< ::block_drawing_msgs::GenerateTrajectoryRequest>
{
  static const char* value()
  {
    return DataType< ::block_drawing_msgs::GenerateTrajectory >::value();
  }
  static const char* value(const ::block_drawing_msgs::GenerateTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::block_drawing_msgs::GenerateTrajectoryResponse> should match
// service_traits::MD5Sum< ::block_drawing_msgs::GenerateTrajectory >
template<>
struct MD5Sum< ::block_drawing_msgs::GenerateTrajectoryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::block_drawing_msgs::GenerateTrajectory >::value();
  }
  static const char* value(const ::block_drawing_msgs::GenerateTrajectoryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::block_drawing_msgs::GenerateTrajectoryResponse> should match
// service_traits::DataType< ::block_drawing_msgs::GenerateTrajectory >
template<>
struct DataType< ::block_drawing_msgs::GenerateTrajectoryResponse>
{
  static const char* value()
  {
    return DataType< ::block_drawing_msgs::GenerateTrajectory >::value();
  }
  static const char* value(const ::block_drawing_msgs::GenerateTrajectoryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BLOCK_DRAWING_MSGS_MESSAGE_GENERATETRAJECTORY_H
