// Generated by gencpp from file block_drawing_msgs/GenerateTrajectoryRequest.msg
// DO NOT EDIT!


#ifndef BLOCK_DRAWING_MSGS_MESSAGE_GENERATETRAJECTORYREQUEST_H
#define BLOCK_DRAWING_MSGS_MESSAGE_GENERATETRAJECTORYREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace block_drawing_msgs
{
template <class ContainerAllocator>
struct GenerateTrajectoryRequest_
{
  typedef GenerateTrajectoryRequest_<ContainerAllocator> Type;

  GenerateTrajectoryRequest_()
    : svg_file()
    , target_width_mm(0.0)
    , target_height_mm(0.0)
    , faces()
    , test_pattern()  {
    }
  GenerateTrajectoryRequest_(const ContainerAllocator& _alloc)
    : svg_file(_alloc)
    , target_width_mm(0.0)
    , target_height_mm(0.0)
    , faces(_alloc)
    , test_pattern(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _svg_file_type;
  _svg_file_type svg_file;

   typedef double _target_width_mm_type;
  _target_width_mm_type target_width_mm;

   typedef double _target_height_mm_type;
  _target_height_mm_type target_height_mm;

   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _faces_type;
  _faces_type faces;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _test_pattern_type;
  _test_pattern_type test_pattern;





  typedef boost::shared_ptr< ::block_drawing_msgs::GenerateTrajectoryRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::block_drawing_msgs::GenerateTrajectoryRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GenerateTrajectoryRequest_

typedef ::block_drawing_msgs::GenerateTrajectoryRequest_<std::allocator<void> > GenerateTrajectoryRequest;

typedef boost::shared_ptr< ::block_drawing_msgs::GenerateTrajectoryRequest > GenerateTrajectoryRequestPtr;
typedef boost::shared_ptr< ::block_drawing_msgs::GenerateTrajectoryRequest const> GenerateTrajectoryRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::block_drawing_msgs::GenerateTrajectoryRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::block_drawing_msgs::GenerateTrajectoryRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::block_drawing_msgs::GenerateTrajectoryRequest_<ContainerAllocator1> & lhs, const ::block_drawing_msgs::GenerateTrajectoryRequest_<ContainerAllocator2> & rhs)
{
  return lhs.svg_file == rhs.svg_file &&
    lhs.target_width_mm == rhs.target_width_mm &&
    lhs.target_height_mm == rhs.target_height_mm &&
    lhs.faces == rhs.faces &&
    lhs.test_pattern == rhs.test_pattern;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::block_drawing_msgs::GenerateTrajectoryRequest_<ContainerAllocator1> & lhs, const ::block_drawing_msgs::GenerateTrajectoryRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace block_drawing_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::block_drawing_msgs::GenerateTrajectoryRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::block_drawing_msgs::GenerateTrajectoryRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::block_drawing_msgs::GenerateTrajectoryRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::block_drawing_msgs::GenerateTrajectoryRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::block_drawing_msgs::GenerateTrajectoryRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::block_drawing_msgs::GenerateTrajectoryRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::block_drawing_msgs::GenerateTrajectoryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "101569b0caf27e51af004362761e0107";
  }

  static const char* value(const ::block_drawing_msgs::GenerateTrajectoryRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x101569b0caf27e51ULL;
  static const uint64_t static_value2 = 0xaf004362761e0107ULL;
};

template<class ContainerAllocator>
struct DataType< ::block_drawing_msgs::GenerateTrajectoryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "block_drawing_msgs/GenerateTrajectoryRequest";
  }

  static const char* value(const ::block_drawing_msgs::GenerateTrajectoryRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::block_drawing_msgs::GenerateTrajectoryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# GenerateTrajectory.srv\n"
"# 模块A服务: SVG/图案 → 轨迹序列\n"
"\n"
"string   svg_file                          # SVG文件路径 (空=使用内置测试图案)\n"
"float64  target_width_mm                   # 目标图案宽度 [mm]\n"
"float64  target_height_mm                  # 目标图案高度 [mm]\n"
"int32[]  faces                             # 要画的面的列表 (0~4)\n"
"string   test_pattern                      # 内置测试图案类型: \"square\" / \"circle\" / \"star\" (svg_file为空时生效)\n"
;
  }

  static const char* value(const ::block_drawing_msgs::GenerateTrajectoryRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::block_drawing_msgs::GenerateTrajectoryRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.svg_file);
      stream.next(m.target_width_mm);
      stream.next(m.target_height_mm);
      stream.next(m.faces);
      stream.next(m.test_pattern);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GenerateTrajectoryRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::block_drawing_msgs::GenerateTrajectoryRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::block_drawing_msgs::GenerateTrajectoryRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "svg_file: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.svg_file);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "target_width_mm: ";
    Printer<double>::stream(s, indent + "  ", v.target_width_mm);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "target_height_mm: ";
    Printer<double>::stream(s, indent + "  ", v.target_height_mm);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "faces: ";
    if (v.faces.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.faces.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<int32_t>::stream(s, true ? std::string() : indent + "    ", v.faces[i]);
    }
    if (v.faces.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "test_pattern: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.test_pattern);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BLOCK_DRAWING_MSGS_MESSAGE_GENERATETRAJECTORYREQUEST_H
