// Generated by gencpp from file block_drawing_msgs/GenerateTrajectoryResponse.msg
// DO NOT EDIT!


#ifndef BLOCK_DRAWING_MSGS_MESSAGE_GENERATETRAJECTORYRESPONSE_H
#define BLOCK_DRAWING_MSGS_MESSAGE_GENERATETRAJECTORYRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <block_drawing_msgs/SurfaceTrajectory.h>

namespace block_drawing_msgs
{
template <class ContainerAllocator>
struct GenerateTrajectoryResponse_
{
  typedef GenerateTrajectoryResponse_<ContainerAllocator> Type;

  GenerateTrajectoryResponse_()
    : trajectories()
    , success(false)
    , message()  {
    }
  GenerateTrajectoryResponse_(const ContainerAllocator& _alloc)
    : trajectories(_alloc)
    , success(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::block_drawing_msgs::SurfaceTrajectory_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::block_drawing_msgs::SurfaceTrajectory_<ContainerAllocator> >> _trajectories_type;
  _trajectories_type trajectories;

   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::block_drawing_msgs::GenerateTrajectoryResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::block_drawing_msgs::GenerateTrajectoryResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GenerateTrajectoryResponse_

typedef ::block_drawing_msgs::GenerateTrajectoryResponse_<std::allocator<void> > GenerateTrajectoryResponse;

typedef boost::shared_ptr< ::block_drawing_msgs::GenerateTrajectoryResponse > GenerateTrajectoryResponsePtr;
typedef boost::shared_ptr< ::block_drawing_msgs::GenerateTrajectoryResponse const> GenerateTrajectoryResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::block_drawing_msgs::GenerateTrajectoryResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::block_drawing_msgs::GenerateTrajectoryResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::block_drawing_msgs::GenerateTrajectoryResponse_<ContainerAllocator1> & lhs, const ::block_drawing_msgs::GenerateTrajectoryResponse_<ContainerAllocator2> & rhs)
{
  return lhs.trajectories == rhs.trajectories &&
    lhs.success == rhs.success &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::block_drawing_msgs::GenerateTrajectoryResponse_<ContainerAllocator1> & lhs, const ::block_drawing_msgs::GenerateTrajectoryResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace block_drawing_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::block_drawing_msgs::GenerateTrajectoryResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::block_drawing_msgs::GenerateTrajectoryResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::block_drawing_msgs::GenerateTrajectoryResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::block_drawing_msgs::GenerateTrajectoryResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::block_drawing_msgs::GenerateTrajectoryResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::block_drawing_msgs::GenerateTrajectoryResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::block_drawing_msgs::GenerateTrajectoryResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "42f26797fa281018517161f56d37f514";
  }

  static const char* value(const ::block_drawing_msgs::GenerateTrajectoryResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x42f26797fa281018ULL;
  static const uint64_t static_value2 = 0x517161f56d37f514ULL;
};

template<class ContainerAllocator>
struct DataType< ::block_drawing_msgs::GenerateTrajectoryResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "block_drawing_msgs/GenerateTrajectoryResponse";
  }

  static const char* value(const ::block_drawing_msgs::GenerateTrajectoryResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::block_drawing_msgs::GenerateTrajectoryResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "block_drawing_msgs/SurfaceTrajectory[] trajectories  # 每个面对应一条轨迹\n"
"bool     success\n"
"string   message\n"
"\n"
"\n"
"================================================================================\n"
"MSG: block_drawing_msgs/SurfaceTrajectory\n"
"# SurfaceTrajectory.msg\n"
"# 单面轨迹: 包含该面所有 waypoints\n"
"\n"
"int32   face_id                    # 0=顶面, 1=前面, 2=右面, 3=后面, 4=左面\n"
"geometry_msgs/Pose[] waypoints     # 末端期望位姿 (含法兰补偿)\n"
"float64[] arc_lengths              # 累计弧长, 用于速度规划 [m]\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::block_drawing_msgs::GenerateTrajectoryResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::block_drawing_msgs::GenerateTrajectoryResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.trajectories);
      stream.next(m.success);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GenerateTrajectoryResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::block_drawing_msgs::GenerateTrajectoryResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::block_drawing_msgs::GenerateTrajectoryResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "trajectories: ";
    if (v.trajectories.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.trajectories.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::block_drawing_msgs::SurfaceTrajectory_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.trajectories[i]);
    }
    if (v.trajectories.empty() || false)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BLOCK_DRAWING_MSGS_MESSAGE_GENERATETRAJECTORYRESPONSE_H
