// Generated by gencpp from file block_drawing_msgs/SetBlockPoseRequest.msg
// DO NOT EDIT!


#ifndef BLOCK_DRAWING_MSGS_MESSAGE_SETBLOCKPOSEREQUEST_H
#define BLOCK_DRAWING_MSGS_MESSAGE_SETBLOCKPOSEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace block_drawing_msgs
{
template <class ContainerAllocator>
struct SetBlockPoseRequest_
{
  typedef SetBlockPoseRequest_<ContainerAllocator> Type;

  SetBlockPoseRequest_()
    : block_pose()
    , L(0.0)
    , W(0.0)
    , H(0.0)
    , face_offset_u()
    , face_offset_v()
    , center_face(0)
    , center_u_mm(0.0)
    , center_v_mm(0.0)  {
      face_offset_u.assign(0.0);

      face_offset_v.assign(0.0);
  }
  SetBlockPoseRequest_(const ContainerAllocator& _alloc)
    : block_pose(_alloc)
    , L(0.0)
    , W(0.0)
    , H(0.0)
    , face_offset_u()
    , face_offset_v()
    , center_face(0)
    , center_u_mm(0.0)
    , center_v_mm(0.0)  {
  (void)_alloc;
      face_offset_u.assign(0.0);

      face_offset_v.assign(0.0);
  }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _block_pose_type;
  _block_pose_type block_pose;

   typedef double _L_type;
  _L_type L;

   typedef double _W_type;
  _W_type W;

   typedef double _H_type;
  _H_type H;

   typedef boost::array<double, 5>  _face_offset_u_type;
  _face_offset_u_type face_offset_u;

   typedef boost::array<double, 5>  _face_offset_v_type;
  _face_offset_v_type face_offset_v;

   typedef int32_t _center_face_type;
  _center_face_type center_face;

   typedef double _center_u_mm_type;
  _center_u_mm_type center_u_mm;

   typedef double _center_v_mm_type;
  _center_v_mm_type center_v_mm;





  typedef boost::shared_ptr< ::block_drawing_msgs::SetBlockPoseRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::block_drawing_msgs::SetBlockPoseRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetBlockPoseRequest_

typedef ::block_drawing_msgs::SetBlockPoseRequest_<std::allocator<void> > SetBlockPoseRequest;

typedef boost::shared_ptr< ::block_drawing_msgs::SetBlockPoseRequest > SetBlockPoseRequestPtr;
typedef boost::shared_ptr< ::block_drawing_msgs::SetBlockPoseRequest const> SetBlockPoseRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::block_drawing_msgs::SetBlockPoseRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::block_drawing_msgs::SetBlockPoseRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::block_drawing_msgs::SetBlockPoseRequest_<ContainerAllocator1> & lhs, const ::block_drawing_msgs::SetBlockPoseRequest_<ContainerAllocator2> & rhs)
{
  return lhs.block_pose == rhs.block_pose &&
    lhs.L == rhs.L &&
    lhs.W == rhs.W &&
    lhs.H == rhs.H &&
    lhs.face_offset_u == rhs.face_offset_u &&
    lhs.face_offset_v == rhs.face_offset_v &&
    lhs.center_face == rhs.center_face &&
    lhs.center_u_mm == rhs.center_u_mm &&
    lhs.center_v_mm == rhs.center_v_mm;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::block_drawing_msgs::SetBlockPoseRequest_<ContainerAllocator1> & lhs, const ::block_drawing_msgs::SetBlockPoseRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace block_drawing_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::block_drawing_msgs::SetBlockPoseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::block_drawing_msgs::SetBlockPoseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::block_drawing_msgs::SetBlockPoseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::block_drawing_msgs::SetBlockPoseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::block_drawing_msgs::SetBlockPoseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::block_drawing_msgs::SetBlockPoseRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::block_drawing_msgs::SetBlockPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0fd2dcc60a20d920ebc1d9f65ead0ab0";
  }

  static const char* value(const ::block_drawing_msgs::SetBlockPoseRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0fd2dcc60a20d920ULL;
  static const uint64_t static_value2 = 0xebc1d9f65ead0ab0ULL;
};

template<class ContainerAllocator>
struct DataType< ::block_drawing_msgs::SetBlockPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "block_drawing_msgs/SetBlockPoseRequest";
  }

  static const char* value(const ::block_drawing_msgs::SetBlockPoseRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::block_drawing_msgs::SetBlockPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# SetBlockPose.srv\n"
"# 设置物块在机械臂基坐标系下的位姿、尺寸、以及各面的图案投影偏移\n"
"\n"
"geometry_msgs/Pose   block_pose    # T_block_base (物块底面中心→基座)\n"
"float64 L                          # 物块长 [m]\n"
"float64 W                          # 物块宽 [m]\n"
"float64 H                          # 物块高 [m]\n"
"\n"
"# 各面图案投影偏移 [mm], 相对于面中心\n"
"# face_offset_u[i]: 沿面内 u 轴偏移, face_offset_v[i]: 沿面内 v 轴偏移\n"
"# i=0顶面, 1前面, 2右面, 3后面, 4左面\n"
"# 默认全0 = 图案中心对齐面中心\n"
"float64[5] face_offset_u          # 每面 u 向偏移 [mm] (独立面模式)\n"
"float64[5] face_offset_v          # 每面 v 向偏移 [mm] (独立面模式)\n"
"\n"
"# 跨面连续模式: 图案中心在块表面上的锚点\n"
"# center_face = -1 表示使用独立面模式 (每个面独立画)\n"
"# center_face = 0~4 时使用连续模式, 图案从此面此点出发, 超界自动跨邻面\n"
"int32    center_face              # -1=独立面模式, 0~4=连续模式起始面\n"
"float64  center_u_mm              # 图案中心 u 坐标 [mm]\n"
"float64  center_v_mm              # 图案中心 v 坐标 [mm]\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::block_drawing_msgs::SetBlockPoseRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::block_drawing_msgs::SetBlockPoseRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.block_pose);
      stream.next(m.L);
      stream.next(m.W);
      stream.next(m.H);
      stream.next(m.face_offset_u);
      stream.next(m.face_offset_v);
      stream.next(m.center_face);
      stream.next(m.center_u_mm);
      stream.next(m.center_v_mm);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetBlockPoseRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::block_drawing_msgs::SetBlockPoseRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::block_drawing_msgs::SetBlockPoseRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "block_pose: ";
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.block_pose);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "L: ";
    Printer<double>::stream(s, indent + "  ", v.L);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "W: ";
    Printer<double>::stream(s, indent + "  ", v.W);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "H: ";
    Printer<double>::stream(s, indent + "  ", v.H);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "face_offset_u: ";
    if (v.face_offset_u.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.face_offset_u.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.face_offset_u[i]);
    }
    if (v.face_offset_u.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "face_offset_v: ";
    if (v.face_offset_v.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.face_offset_v.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.face_offset_v[i]);
    }
    if (v.face_offset_v.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "center_face: ";
    Printer<int32_t>::stream(s, indent + "  ", v.center_face);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "center_u_mm: ";
    Printer<double>::stream(s, indent + "  ", v.center_u_mm);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "center_v_mm: ";
    Printer<double>::stream(s, indent + "  ", v.center_v_mm);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BLOCK_DRAWING_MSGS_MESSAGE_SETBLOCKPOSEREQUEST_H
