// Generated by gencpp from file block_drawing_msgs/SurfaceTrajectory.msg
// DO NOT EDIT!


#ifndef BLOCK_DRAWING_MSGS_MESSAGE_SURFACETRAJECTORY_H
#define BLOCK_DRAWING_MSGS_MESSAGE_SURFACETRAJECTORY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace block_drawing_msgs
{
template <class ContainerAllocator>
struct SurfaceTrajectory_
{
  typedef SurfaceTrajectory_<ContainerAllocator> Type;

  SurfaceTrajectory_()
    : face_id(0)
    , waypoints()
    , arc_lengths()  {
    }
  SurfaceTrajectory_(const ContainerAllocator& _alloc)
    : face_id(0)
    , waypoints(_alloc)
    , arc_lengths(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _face_id_type;
  _face_id_type face_id;

   typedef std::vector< ::geometry_msgs::Pose_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Pose_<ContainerAllocator> >> _waypoints_type;
  _waypoints_type waypoints;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _arc_lengths_type;
  _arc_lengths_type arc_lengths;





  typedef boost::shared_ptr< ::block_drawing_msgs::SurfaceTrajectory_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::block_drawing_msgs::SurfaceTrajectory_<ContainerAllocator> const> ConstPtr;

}; // struct SurfaceTrajectory_

typedef ::block_drawing_msgs::SurfaceTrajectory_<std::allocator<void> > SurfaceTrajectory;

typedef boost::shared_ptr< ::block_drawing_msgs::SurfaceTrajectory > SurfaceTrajectoryPtr;
typedef boost::shared_ptr< ::block_drawing_msgs::SurfaceTrajectory const> SurfaceTrajectoryConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::block_drawing_msgs::SurfaceTrajectory_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::block_drawing_msgs::SurfaceTrajectory_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::block_drawing_msgs::SurfaceTrajectory_<ContainerAllocator1> & lhs, const ::block_drawing_msgs::SurfaceTrajectory_<ContainerAllocator2> & rhs)
{
  return lhs.face_id == rhs.face_id &&
    lhs.waypoints == rhs.waypoints &&
    lhs.arc_lengths == rhs.arc_lengths;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::block_drawing_msgs::SurfaceTrajectory_<ContainerAllocator1> & lhs, const ::block_drawing_msgs::SurfaceTrajectory_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace block_drawing_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::block_drawing_msgs::SurfaceTrajectory_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::block_drawing_msgs::SurfaceTrajectory_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::block_drawing_msgs::SurfaceTrajectory_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::block_drawing_msgs::SurfaceTrajectory_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::block_drawing_msgs::SurfaceTrajectory_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::block_drawing_msgs::SurfaceTrajectory_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::block_drawing_msgs::SurfaceTrajectory_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5b572666885f29b8eb6f14e36c9ed7c7";
  }

  static const char* value(const ::block_drawing_msgs::SurfaceTrajectory_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5b572666885f29b8ULL;
  static const uint64_t static_value2 = 0xeb6f14e36c9ed7c7ULL;
};

template<class ContainerAllocator>
struct DataType< ::block_drawing_msgs::SurfaceTrajectory_<ContainerAllocator> >
{
  static const char* value()
  {
    return "block_drawing_msgs/SurfaceTrajectory";
  }

  static const char* value(const ::block_drawing_msgs::SurfaceTrajectory_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::block_drawing_msgs::SurfaceTrajectory_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# SurfaceTrajectory.msg\n"
"# 单面轨迹: 包含该面所有 waypoints\n"
"\n"
"int32   face_id                    # 0=顶面, 1=前面, 2=右面, 3=后面, 4=左面\n"
"geometry_msgs/Pose[] waypoints     # 末端期望位姿 (含法兰补偿)\n"
"float64[] arc_lengths              # 累计弧长, 用于速度规划 [m]\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::block_drawing_msgs::SurfaceTrajectory_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::block_drawing_msgs::SurfaceTrajectory_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.face_id);
      stream.next(m.waypoints);
      stream.next(m.arc_lengths);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SurfaceTrajectory_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::block_drawing_msgs::SurfaceTrajectory_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::block_drawing_msgs::SurfaceTrajectory_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "face_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.face_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "waypoints: ";
    if (v.waypoints.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.waypoints.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.waypoints[i]);
    }
    if (v.waypoints.empty() || false)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "arc_lengths: ";
    if (v.arc_lengths.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.arc_lengths.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.arc_lengths[i]);
    }
    if (v.arc_lengths.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // BLOCK_DRAWING_MSGS_MESSAGE_SURFACETRAJECTORY_H
