# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from kortex_driver/Base_GpioConfiguration.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import kortex_driver.msg

class Base_GpioConfiguration(genpy.Message):
  _md5sum = "92f1de7cd4a1d8641179ab50f182b3f3"
  _type = "kortex_driver/Base_GpioConfiguration"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """
uint32 port_number
GpioPinConfiguration[] pin_configurations
================================================================================
MSG: kortex_driver/GpioPinConfiguration

uint32 pin_id
uint32 pin_property
bool output_enable
bool default_output_value"""
  __slots__ = ['port_number','pin_configurations']
  _slot_types = ['uint32','kortex_driver/GpioPinConfiguration[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       port_number,pin_configurations

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Base_GpioConfiguration, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.port_number is None:
        self.port_number = 0
      if self.pin_configurations is None:
        self.pin_configurations = []
    else:
      self.port_number = 0
      self.pin_configurations = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.port_number
      buff.write(_get_struct_I().pack(_x))
      length = len(self.pin_configurations)
      buff.write(_struct_I.pack(length))
      for val1 in self.pin_configurations:
        _x = val1
        buff.write(_get_struct_2I2B().pack(_x.pin_id, _x.pin_property, _x.output_enable, _x.default_output_value))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.pin_configurations is None:
        self.pin_configurations = None
      end = 0
      start = end
      end += 4
      (self.port_number,) = _get_struct_I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.pin_configurations = []
      for i in range(0, length):
        val1 = kortex_driver.msg.GpioPinConfiguration()
        _x = val1
        start = end
        end += 10
        (_x.pin_id, _x.pin_property, _x.output_enable, _x.default_output_value,) = _get_struct_2I2B().unpack(str[start:end])
        val1.output_enable = bool(val1.output_enable)
        val1.default_output_value = bool(val1.default_output_value)
        self.pin_configurations.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.port_number
      buff.write(_get_struct_I().pack(_x))
      length = len(self.pin_configurations)
      buff.write(_struct_I.pack(length))
      for val1 in self.pin_configurations:
        _x = val1
        buff.write(_get_struct_2I2B().pack(_x.pin_id, _x.pin_property, _x.output_enable, _x.default_output_value))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.pin_configurations is None:
        self.pin_configurations = None
      end = 0
      start = end
      end += 4
      (self.port_number,) = _get_struct_I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.pin_configurations = []
      for i in range(0, length):
        val1 = kortex_driver.msg.GpioPinConfiguration()
        _x = val1
        start = end
        end += 10
        (_x.pin_id, _x.pin_property, _x.output_enable, _x.default_output_value,) = _get_struct_2I2B().unpack(str[start:end])
        val1.output_enable = bool(val1.output_enable)
        val1.default_output_value = bool(val1.default_output_value)
        self.pin_configurations.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2I2B = None
def _get_struct_2I2B():
    global _struct_2I2B
    if _struct_2I2B is None:
        _struct_2I2B = struct.Struct("<2I2B")
    return _struct_2I2B
