# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from kortex_driver/CartesianWaypoint.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import kortex_driver.msg

class CartesianWaypoint(genpy.Message):
  _md5sum = "057d3bd32497f1e96612efc0fb6ef690"
  _type = "kortex_driver/CartesianWaypoint"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """
Pose pose
uint32 reference_frame
float32 maximum_linear_velocity
float32 maximum_angular_velocity
float32 blending_radius
================================================================================
MSG: kortex_driver/Pose

float32 x
float32 y
float32 z
float32 theta_x
float32 theta_y
float32 theta_z"""
  __slots__ = ['pose','reference_frame','maximum_linear_velocity','maximum_angular_velocity','blending_radius']
  _slot_types = ['kortex_driver/Pose','uint32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       pose,reference_frame,maximum_linear_velocity,maximum_angular_velocity,blending_radius

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(CartesianWaypoint, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.pose is None:
        self.pose = kortex_driver.msg.Pose()
      if self.reference_frame is None:
        self.reference_frame = 0
      if self.maximum_linear_velocity is None:
        self.maximum_linear_velocity = 0.
      if self.maximum_angular_velocity is None:
        self.maximum_angular_velocity = 0.
      if self.blending_radius is None:
        self.blending_radius = 0.
    else:
      self.pose = kortex_driver.msg.Pose()
      self.reference_frame = 0
      self.maximum_linear_velocity = 0.
      self.maximum_angular_velocity = 0.
      self.blending_radius = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6fI3f().pack(_x.pose.x, _x.pose.y, _x.pose.z, _x.pose.theta_x, _x.pose.theta_y, _x.pose.theta_z, _x.reference_frame, _x.maximum_linear_velocity, _x.maximum_angular_velocity, _x.blending_radius))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.pose is None:
        self.pose = kortex_driver.msg.Pose()
      end = 0
      _x = self
      start = end
      end += 40
      (_x.pose.x, _x.pose.y, _x.pose.z, _x.pose.theta_x, _x.pose.theta_y, _x.pose.theta_z, _x.reference_frame, _x.maximum_linear_velocity, _x.maximum_angular_velocity, _x.blending_radius,) = _get_struct_6fI3f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6fI3f().pack(_x.pose.x, _x.pose.y, _x.pose.z, _x.pose.theta_x, _x.pose.theta_y, _x.pose.theta_z, _x.reference_frame, _x.maximum_linear_velocity, _x.maximum_angular_velocity, _x.blending_radius))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.pose is None:
        self.pose = kortex_driver.msg.Pose()
      end = 0
      _x = self
      start = end
      end += 40
      (_x.pose.x, _x.pose.y, _x.pose.z, _x.pose.theta_x, _x.pose.theta_y, _x.pose.theta_z, _x.reference_frame, _x.maximum_linear_velocity, _x.maximum_angular_velocity, _x.blending_radius,) = _get_struct_6fI3f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6fI3f = None
def _get_struct_6fI3f():
    global _struct_6fI3f
    if _struct_6fI3f is None:
        _struct_6fI3f = struct.Struct("<6fI3f")
    return _struct_6fI3f
