# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from kortex_driver/FollowCartesianTrajectoryGoal.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy
import kortex_driver.msg

class FollowCartesianTrajectoryGoal(genpy.Message):
  _md5sum = "df06af45264ea735bb204bc1057fde50"
  _type = "kortex_driver/FollowCartesianTrajectoryGoal"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
#The trajectory to follow
CartesianWaypoint[] trajectory
duration goal_time_tolerance
bool use_optimal_blending

================================================================================
MSG: kortex_driver/CartesianWaypoint

Pose pose
uint32 reference_frame
float32 maximum_linear_velocity
float32 maximum_angular_velocity
float32 blending_radius
================================================================================
MSG: kortex_driver/Pose

float32 x
float32 y
float32 z
float32 theta_x
float32 theta_y
float32 theta_z"""
  __slots__ = ['trajectory','goal_time_tolerance','use_optimal_blending']
  _slot_types = ['kortex_driver/CartesianWaypoint[]','duration','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       trajectory,goal_time_tolerance,use_optimal_blending

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(FollowCartesianTrajectoryGoal, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.trajectory is None:
        self.trajectory = []
      if self.goal_time_tolerance is None:
        self.goal_time_tolerance = genpy.Duration()
      if self.use_optimal_blending is None:
        self.use_optimal_blending = False
    else:
      self.trajectory = []
      self.goal_time_tolerance = genpy.Duration()
      self.use_optimal_blending = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.trajectory)
      buff.write(_struct_I.pack(length))
      for val1 in self.trajectory:
        _v1 = val1.pose
        _x = _v1
        buff.write(_get_struct_6f().pack(_x.x, _x.y, _x.z, _x.theta_x, _x.theta_y, _x.theta_z))
        _x = val1
        buff.write(_get_struct_I3f().pack(_x.reference_frame, _x.maximum_linear_velocity, _x.maximum_angular_velocity, _x.blending_radius))
      _x = self
      buff.write(_get_struct_2iB().pack(_x.goal_time_tolerance.secs, _x.goal_time_tolerance.nsecs, _x.use_optimal_blending))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.trajectory is None:
        self.trajectory = None
      if self.goal_time_tolerance is None:
        self.goal_time_tolerance = genpy.Duration()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.trajectory = []
      for i in range(0, length):
        val1 = kortex_driver.msg.CartesianWaypoint()
        _v2 = val1.pose
        _x = _v2
        start = end
        end += 24
        (_x.x, _x.y, _x.z, _x.theta_x, _x.theta_y, _x.theta_z,) = _get_struct_6f().unpack(str[start:end])
        _x = val1
        start = end
        end += 16
        (_x.reference_frame, _x.maximum_linear_velocity, _x.maximum_angular_velocity, _x.blending_radius,) = _get_struct_I3f().unpack(str[start:end])
        self.trajectory.append(val1)
      _x = self
      start = end
      end += 9
      (_x.goal_time_tolerance.secs, _x.goal_time_tolerance.nsecs, _x.use_optimal_blending,) = _get_struct_2iB().unpack(str[start:end])
      self.use_optimal_blending = bool(self.use_optimal_blending)
      self.goal_time_tolerance.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.trajectory)
      buff.write(_struct_I.pack(length))
      for val1 in self.trajectory:
        _v3 = val1.pose
        _x = _v3
        buff.write(_get_struct_6f().pack(_x.x, _x.y, _x.z, _x.theta_x, _x.theta_y, _x.theta_z))
        _x = val1
        buff.write(_get_struct_I3f().pack(_x.reference_frame, _x.maximum_linear_velocity, _x.maximum_angular_velocity, _x.blending_radius))
      _x = self
      buff.write(_get_struct_2iB().pack(_x.goal_time_tolerance.secs, _x.goal_time_tolerance.nsecs, _x.use_optimal_blending))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.trajectory is None:
        self.trajectory = None
      if self.goal_time_tolerance is None:
        self.goal_time_tolerance = genpy.Duration()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.trajectory = []
      for i in range(0, length):
        val1 = kortex_driver.msg.CartesianWaypoint()
        _v4 = val1.pose
        _x = _v4
        start = end
        end += 24
        (_x.x, _x.y, _x.z, _x.theta_x, _x.theta_y, _x.theta_z,) = _get_struct_6f().unpack(str[start:end])
        _x = val1
        start = end
        end += 16
        (_x.reference_frame, _x.maximum_linear_velocity, _x.maximum_angular_velocity, _x.blending_radius,) = _get_struct_I3f().unpack(str[start:end])
        self.trajectory.append(val1)
      _x = self
      start = end
      end += 9
      (_x.goal_time_tolerance.secs, _x.goal_time_tolerance.nsecs, _x.use_optimal_blending,) = _get_struct_2iB().unpack(str[start:end])
      self.use_optimal_blending = bool(self.use_optimal_blending)
      self.goal_time_tolerance.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2iB = None
def _get_struct_2iB():
    global _struct_2iB
    if _struct_2iB is None:
        _struct_2iB = struct.Struct("<2iB")
    return _struct_2iB
_struct_6f = None
def _get_struct_6f():
    global _struct_6f
    if _struct_6f is None:
        _struct_6f = struct.Struct("<6f")
    return _struct_6f
_struct_I3f = None
def _get_struct_I3f():
    global _struct_I3f
    if _struct_I3f is None:
        _struct_I3f = struct.Struct("<I3f")
    return _struct_I3f
