# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from kortex_driver/GpioPinConfiguration.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class GpioPinConfiguration(genpy.Message):
  _md5sum = "4b71615f4756e2920864ba411102db09"
  _type = "kortex_driver/GpioPinConfiguration"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """
uint32 pin_id
uint32 pin_property
bool output_enable
bool default_output_value"""
  __slots__ = ['pin_id','pin_property','output_enable','default_output_value']
  _slot_types = ['uint32','uint32','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       pin_id,pin_property,output_enable,default_output_value

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GpioPinConfiguration, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.pin_id is None:
        self.pin_id = 0
      if self.pin_property is None:
        self.pin_property = 0
      if self.output_enable is None:
        self.output_enable = False
      if self.default_output_value is None:
        self.default_output_value = False
    else:
      self.pin_id = 0
      self.pin_property = 0
      self.output_enable = False
      self.default_output_value = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2I2B().pack(_x.pin_id, _x.pin_property, _x.output_enable, _x.default_output_value))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 10
      (_x.pin_id, _x.pin_property, _x.output_enable, _x.default_output_value,) = _get_struct_2I2B().unpack(str[start:end])
      self.output_enable = bool(self.output_enable)
      self.default_output_value = bool(self.default_output_value)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2I2B().pack(_x.pin_id, _x.pin_property, _x.output_enable, _x.default_output_value))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 10
      (_x.pin_id, _x.pin_property, _x.output_enable, _x.default_output_value,) = _get_struct_2I2B().unpack(str[start:end])
      self.output_enable = bool(self.output_enable)
      self.default_output_value = bool(self.default_output_value)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2I2B = None
def _get_struct_2I2B():
    global _struct_2I2B
    if _struct_2I2B is None:
        _struct_2I2B = struct.Struct("<2I2B")
    return _struct_2I2B
