# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from kortex_driver/WaypointList.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import kortex_driver.msg

class WaypointList(genpy.Message):
  _md5sum = "7b5e341798f530d68dce10b5bad29aad"
  _type = "kortex_driver/WaypointList"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """
Waypoint[] waypoints
float32 duration
bool use_optimal_blending
================================================================================
MSG: kortex_driver/Waypoint

string name
Waypoint_type_of_waypoint oneof_type_of_waypoint
================================================================================
MSG: kortex_driver/Waypoint_type_of_waypoint

AngularWaypoint[] angular_waypoint
CartesianWaypoint[] cartesian_waypoint
================================================================================
MSG: kortex_driver/AngularWaypoint

float32[] angles
float32[] maximum_velocities
float32 duration
================================================================================
MSG: kortex_driver/CartesianWaypoint

Pose pose
uint32 reference_frame
float32 maximum_linear_velocity
float32 maximum_angular_velocity
float32 blending_radius
================================================================================
MSG: kortex_driver/Pose

float32 x
float32 y
float32 z
float32 theta_x
float32 theta_y
float32 theta_z"""
  __slots__ = ['waypoints','duration','use_optimal_blending']
  _slot_types = ['kortex_driver/Waypoint[]','float32','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       waypoints,duration,use_optimal_blending

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(WaypointList, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.waypoints is None:
        self.waypoints = []
      if self.duration is None:
        self.duration = 0.
      if self.use_optimal_blending is None:
        self.use_optimal_blending = False
    else:
      self.waypoints = []
      self.duration = 0.
      self.use_optimal_blending = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.waypoints)
      buff.write(_struct_I.pack(length))
      for val1 in self.waypoints:
        _x = val1.name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _v1 = val1.oneof_type_of_waypoint
        length = len(_v1.angular_waypoint)
        buff.write(_struct_I.pack(length))
        for val3 in _v1.angular_waypoint:
          length = len(val3.angles)
          buff.write(_struct_I.pack(length))
          pattern = '<%sf'%length
          buff.write(struct.Struct(pattern).pack(*val3.angles))
          length = len(val3.maximum_velocities)
          buff.write(_struct_I.pack(length))
          pattern = '<%sf'%length
          buff.write(struct.Struct(pattern).pack(*val3.maximum_velocities))
          _x = val3.duration
          buff.write(_get_struct_f().pack(_x))
        length = len(_v1.cartesian_waypoint)
        buff.write(_struct_I.pack(length))
        for val3 in _v1.cartesian_waypoint:
          _v2 = val3.pose
          _x = _v2
          buff.write(_get_struct_6f().pack(_x.x, _x.y, _x.z, _x.theta_x, _x.theta_y, _x.theta_z))
          _x = val3
          buff.write(_get_struct_I3f().pack(_x.reference_frame, _x.maximum_linear_velocity, _x.maximum_angular_velocity, _x.blending_radius))
      _x = self
      buff.write(_get_struct_fB().pack(_x.duration, _x.use_optimal_blending))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.waypoints is None:
        self.waypoints = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.waypoints = []
      for i in range(0, length):
        val1 = kortex_driver.msg.Waypoint()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.name = str[start:end]
        _v3 = val1.oneof_type_of_waypoint
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        _v3.angular_waypoint = []
        for i in range(0, length):
          val3 = kortex_driver.msg.AngularWaypoint()
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          pattern = '<%sf'%length
          start = end
          s = struct.Struct(pattern)
          end += s.size
          val3.angles = s.unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          pattern = '<%sf'%length
          start = end
          s = struct.Struct(pattern)
          end += s.size
          val3.maximum_velocities = s.unpack(str[start:end])
          start = end
          end += 4
          (val3.duration,) = _get_struct_f().unpack(str[start:end])
          _v3.angular_waypoint.append(val3)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        _v3.cartesian_waypoint = []
        for i in range(0, length):
          val3 = kortex_driver.msg.CartesianWaypoint()
          _v4 = val3.pose
          _x = _v4
          start = end
          end += 24
          (_x.x, _x.y, _x.z, _x.theta_x, _x.theta_y, _x.theta_z,) = _get_struct_6f().unpack(str[start:end])
          _x = val3
          start = end
          end += 16
          (_x.reference_frame, _x.maximum_linear_velocity, _x.maximum_angular_velocity, _x.blending_radius,) = _get_struct_I3f().unpack(str[start:end])
          _v3.cartesian_waypoint.append(val3)
        self.waypoints.append(val1)
      _x = self
      start = end
      end += 5
      (_x.duration, _x.use_optimal_blending,) = _get_struct_fB().unpack(str[start:end])
      self.use_optimal_blending = bool(self.use_optimal_blending)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.waypoints)
      buff.write(_struct_I.pack(length))
      for val1 in self.waypoints:
        _x = val1.name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _v5 = val1.oneof_type_of_waypoint
        length = len(_v5.angular_waypoint)
        buff.write(_struct_I.pack(length))
        for val3 in _v5.angular_waypoint:
          length = len(val3.angles)
          buff.write(_struct_I.pack(length))
          pattern = '<%sf'%length
          buff.write(val3.angles.tostring())
          length = len(val3.maximum_velocities)
          buff.write(_struct_I.pack(length))
          pattern = '<%sf'%length
          buff.write(val3.maximum_velocities.tostring())
          _x = val3.duration
          buff.write(_get_struct_f().pack(_x))
        length = len(_v5.cartesian_waypoint)
        buff.write(_struct_I.pack(length))
        for val3 in _v5.cartesian_waypoint:
          _v6 = val3.pose
          _x = _v6
          buff.write(_get_struct_6f().pack(_x.x, _x.y, _x.z, _x.theta_x, _x.theta_y, _x.theta_z))
          _x = val3
          buff.write(_get_struct_I3f().pack(_x.reference_frame, _x.maximum_linear_velocity, _x.maximum_angular_velocity, _x.blending_radius))
      _x = self
      buff.write(_get_struct_fB().pack(_x.duration, _x.use_optimal_blending))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.waypoints is None:
        self.waypoints = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.waypoints = []
      for i in range(0, length):
        val1 = kortex_driver.msg.Waypoint()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.name = str[start:end]
        _v7 = val1.oneof_type_of_waypoint
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        _v7.angular_waypoint = []
        for i in range(0, length):
          val3 = kortex_driver.msg.AngularWaypoint()
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          pattern = '<%sf'%length
          start = end
          s = struct.Struct(pattern)
          end += s.size
          val3.angles = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          pattern = '<%sf'%length
          start = end
          s = struct.Struct(pattern)
          end += s.size
          val3.maximum_velocities = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
          start = end
          end += 4
          (val3.duration,) = _get_struct_f().unpack(str[start:end])
          _v7.angular_waypoint.append(val3)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        _v7.cartesian_waypoint = []
        for i in range(0, length):
          val3 = kortex_driver.msg.CartesianWaypoint()
          _v8 = val3.pose
          _x = _v8
          start = end
          end += 24
          (_x.x, _x.y, _x.z, _x.theta_x, _x.theta_y, _x.theta_z,) = _get_struct_6f().unpack(str[start:end])
          _x = val3
          start = end
          end += 16
          (_x.reference_frame, _x.maximum_linear_velocity, _x.maximum_angular_velocity, _x.blending_radius,) = _get_struct_I3f().unpack(str[start:end])
          _v7.cartesian_waypoint.append(val3)
        self.waypoints.append(val1)
      _x = self
      start = end
      end += 5
      (_x.duration, _x.use_optimal_blending,) = _get_struct_fB().unpack(str[start:end])
      self.use_optimal_blending = bool(self.use_optimal_blending)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6f = None
def _get_struct_6f():
    global _struct_6f
    if _struct_6f is None:
        _struct_6f = struct.Struct("<6f")
    return _struct_6f
_struct_I3f = None
def _get_struct_I3f():
    global _struct_I3f
    if _struct_I3f is None:
        _struct_I3f = struct.Struct("<I3f")
    return _struct_I3f
_struct_f = None
def _get_struct_f():
    global _struct_f
    if _struct_f is None:
        _struct_f = struct.Struct("<f")
    return _struct_f
_struct_fB = None
def _get_struct_fB():
    global _struct_fB
    if _struct_fB is None:
        _struct_fB = struct.Struct("<fB")
    return _struct_fB
