# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from kortex_driver/ComputeInverseKinematicsRequest.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import kortex_driver.msg

class ComputeInverseKinematicsRequest(genpy.Message):
  _md5sum = "6370dc05021b231d5d0b535bc12d00f3"
  _type = "kortex_driver/ComputeInverseKinematicsRequest"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """IKData input

================================================================================
MSG: kortex_driver/IKData

Pose cartesian_pose
JointAngles guess
================================================================================
MSG: kortex_driver/Pose

float32 x
float32 y
float32 z
float32 theta_x
float32 theta_y
float32 theta_z
================================================================================
MSG: kortex_driver/JointAngles

JointAngle[] joint_angles
================================================================================
MSG: kortex_driver/JointAngle

uint32 joint_identifier
float32 value"""
  __slots__ = ['input']
  _slot_types = ['kortex_driver/IKData']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       input

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ComputeInverseKinematicsRequest, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.input is None:
        self.input = kortex_driver.msg.IKData()
    else:
      self.input = kortex_driver.msg.IKData()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6f().pack(_x.input.cartesian_pose.x, _x.input.cartesian_pose.y, _x.input.cartesian_pose.z, _x.input.cartesian_pose.theta_x, _x.input.cartesian_pose.theta_y, _x.input.cartesian_pose.theta_z))
      length = len(self.input.guess.joint_angles)
      buff.write(_struct_I.pack(length))
      for val1 in self.input.guess.joint_angles:
        _x = val1
        buff.write(_get_struct_If().pack(_x.joint_identifier, _x.value))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.input is None:
        self.input = kortex_driver.msg.IKData()
      end = 0
      _x = self
      start = end
      end += 24
      (_x.input.cartesian_pose.x, _x.input.cartesian_pose.y, _x.input.cartesian_pose.z, _x.input.cartesian_pose.theta_x, _x.input.cartesian_pose.theta_y, _x.input.cartesian_pose.theta_z,) = _get_struct_6f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.input.guess.joint_angles = []
      for i in range(0, length):
        val1 = kortex_driver.msg.JointAngle()
        _x = val1
        start = end
        end += 8
        (_x.joint_identifier, _x.value,) = _get_struct_If().unpack(str[start:end])
        self.input.guess.joint_angles.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6f().pack(_x.input.cartesian_pose.x, _x.input.cartesian_pose.y, _x.input.cartesian_pose.z, _x.input.cartesian_pose.theta_x, _x.input.cartesian_pose.theta_y, _x.input.cartesian_pose.theta_z))
      length = len(self.input.guess.joint_angles)
      buff.write(_struct_I.pack(length))
      for val1 in self.input.guess.joint_angles:
        _x = val1
        buff.write(_get_struct_If().pack(_x.joint_identifier, _x.value))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.input is None:
        self.input = kortex_driver.msg.IKData()
      end = 0
      _x = self
      start = end
      end += 24
      (_x.input.cartesian_pose.x, _x.input.cartesian_pose.y, _x.input.cartesian_pose.z, _x.input.cartesian_pose.theta_x, _x.input.cartesian_pose.theta_y, _x.input.cartesian_pose.theta_z,) = _get_struct_6f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.input.guess.joint_angles = []
      for i in range(0, length):
        val1 = kortex_driver.msg.JointAngle()
        _x = val1
        start = end
        end += 8
        (_x.joint_identifier, _x.value,) = _get_struct_If().unpack(str[start:end])
        self.input.guess.joint_angles.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6f = None
def _get_struct_6f():
    global _struct_6f
    if _struct_6f is None:
        _struct_6f = struct.Struct("<6f")
    return _struct_6f
_struct_If = None
def _get_struct_If():
    global _struct_If
    if _struct_If is None:
        _struct_If = struct.Struct("<If")
    return _struct_If
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from kortex_driver/ComputeInverseKinematicsResponse.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import kortex_driver.msg

class ComputeInverseKinematicsResponse(genpy.Message):
  _md5sum = "57ef940a22a8b164beebfd955a89b3bb"
  _type = "kortex_driver/ComputeInverseKinematicsResponse"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """JointAngles output

================================================================================
MSG: kortex_driver/JointAngles

JointAngle[] joint_angles
================================================================================
MSG: kortex_driver/JointAngle

uint32 joint_identifier
float32 value"""
  __slots__ = ['output']
  _slot_types = ['kortex_driver/JointAngles']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       output

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ComputeInverseKinematicsResponse, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.output is None:
        self.output = kortex_driver.msg.JointAngles()
    else:
      self.output = kortex_driver.msg.JointAngles()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.output.joint_angles)
      buff.write(_struct_I.pack(length))
      for val1 in self.output.joint_angles:
        _x = val1
        buff.write(_get_struct_If().pack(_x.joint_identifier, _x.value))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.output is None:
        self.output = kortex_driver.msg.JointAngles()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.output.joint_angles = []
      for i in range(0, length):
        val1 = kortex_driver.msg.JointAngle()
        _x = val1
        start = end
        end += 8
        (_x.joint_identifier, _x.value,) = _get_struct_If().unpack(str[start:end])
        self.output.joint_angles.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.output.joint_angles)
      buff.write(_struct_I.pack(length))
      for val1 in self.output.joint_angles:
        _x = val1
        buff.write(_get_struct_If().pack(_x.joint_identifier, _x.value))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.output is None:
        self.output = kortex_driver.msg.JointAngles()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.output.joint_angles = []
      for i in range(0, length):
        val1 = kortex_driver.msg.JointAngle()
        _x = val1
        start = end
        end += 8
        (_x.joint_identifier, _x.value,) = _get_struct_If().unpack(str[start:end])
        self.output.joint_angles.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_If = None
def _get_struct_If():
    global _struct_If
    if _struct_If is None:
        _struct_If = struct.Struct("<If")
    return _struct_If
class ComputeInverseKinematics(object):
  _type          = 'kortex_driver/ComputeInverseKinematics'
  _md5sum = '290825a1e5de199dc18075d261a5fee3'
  _request_class  = ComputeInverseKinematicsRequest
  _response_class = ComputeInverseKinematicsResponse
