(cl:defpackage block_drawing_msgs-msg
  (:use )
  (:export
   "<CONTACTSTATE>"
   "CONTACTSTATE"
   "<DRAWINGEXECUTIONACTION>"
   "DRAWINGEXECUTIONACTION"
   "<DRAWINGEXECUTIONACTIONFEEDBACK>"
   "DRAWINGEXECUTIONACTIONFEEDBACK"
   "<DRAWINGEXECUTIONACTIONGOAL>"
   "DRAWINGEXECUTIONACTIONGOAL"
   "<DRAWINGEXECUTIONACTIONRESULT>"
   "DRAWINGEXECUTIONACTIONRESULT"
   "<DRAWINGEXECUTIONFEEDBACK>"
   "DRAWINGEXECUTIONFEEDBACK"
   "<DRAWINGEXECUTIONGOAL>"
   "DRAWINGEXECUTIONGOAL"
   "<DRAWINGEXECUTIONRESULT>"
   "DRAWINGEXECUTIONRESULT"
   "<SURFACETRAJECTORY>"
   "SURFACETRAJECTORY"
  ))

