// Generated by gencpp from file kortex_driver/ActionNotificationList.msg
// DO NOT EDIT!


#ifndef KORTEX_DRIVER_MESSAGE_ACTIONNOTIFICATIONLIST_H
#define KORTEX_DRIVER_MESSAGE_ACTIONNOTIFICATIONLIST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <kortex_driver/ActionNotification.h>

namespace kortex_driver
{
template <class ContainerAllocator>
struct ActionNotificationList_
{
  typedef ActionNotificationList_<ContainerAllocator> Type;

  ActionNotificationList_()
    : notifications()  {
    }
  ActionNotificationList_(const ContainerAllocator& _alloc)
    : notifications(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::kortex_driver::ActionNotification_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::kortex_driver::ActionNotification_<ContainerAllocator> >> _notifications_type;
  _notifications_type notifications;





  typedef boost::shared_ptr< ::kortex_driver::ActionNotificationList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kortex_driver::ActionNotificationList_<ContainerAllocator> const> ConstPtr;

}; // struct ActionNotificationList_

typedef ::kortex_driver::ActionNotificationList_<std::allocator<void> > ActionNotificationList;

typedef boost::shared_ptr< ::kortex_driver::ActionNotificationList > ActionNotificationListPtr;
typedef boost::shared_ptr< ::kortex_driver::ActionNotificationList const> ActionNotificationListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kortex_driver::ActionNotificationList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kortex_driver::ActionNotificationList_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kortex_driver::ActionNotificationList_<ContainerAllocator1> & lhs, const ::kortex_driver::ActionNotificationList_<ContainerAllocator2> & rhs)
{
  return lhs.notifications == rhs.notifications;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kortex_driver::ActionNotificationList_<ContainerAllocator1> & lhs, const ::kortex_driver::ActionNotificationList_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kortex_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::kortex_driver::ActionNotificationList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kortex_driver::ActionNotificationList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kortex_driver::ActionNotificationList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kortex_driver::ActionNotificationList_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kortex_driver::ActionNotificationList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kortex_driver::ActionNotificationList_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kortex_driver::ActionNotificationList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "352928abe7de8be0e08fbb370dcfa5cb";
  }

  static const char* value(const ::kortex_driver::ActionNotificationList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x352928abe7de8be0ULL;
  static const uint64_t static_value2 = 0xe08fbb370dcfa5cbULL;
};

template<class ContainerAllocator>
struct DataType< ::kortex_driver::ActionNotificationList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kortex_driver/ActionNotificationList";
  }

  static const char* value(const ::kortex_driver::ActionNotificationList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kortex_driver::ActionNotificationList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"ActionNotification[] notifications\n"
"================================================================================\n"
"MSG: kortex_driver/ActionNotification\n"
"\n"
"uint32 action_event\n"
"ActionHandle handle\n"
"Timestamp timestamp\n"
"UserProfileHandle user_handle\n"
"uint32 abort_details\n"
"Connection connection\n"
"TrajectoryInfo[] trajectory_info\n"
"================================================================================\n"
"MSG: kortex_driver/ActionHandle\n"
"\n"
"uint32 identifier\n"
"uint32 action_type\n"
"uint32 permission\n"
"================================================================================\n"
"MSG: kortex_driver/Timestamp\n"
"\n"
"uint32 sec\n"
"uint32 usec\n"
"================================================================================\n"
"MSG: kortex_driver/UserProfileHandle\n"
"\n"
"uint32 identifier\n"
"uint32 permission\n"
"================================================================================\n"
"MSG: kortex_driver/Connection\n"
"\n"
"UserProfileHandle user_handle\n"
"string connection_information\n"
"uint32 connection_identifier\n"
"================================================================================\n"
"MSG: kortex_driver/TrajectoryInfo\n"
"\n"
"uint32 trajectory_info_type\n"
"uint32 waypoint_index\n"
"uint32 joint_index\n"
;
  }

  static const char* value(const ::kortex_driver::ActionNotificationList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kortex_driver::ActionNotificationList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.notifications);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ActionNotificationList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kortex_driver::ActionNotificationList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kortex_driver::ActionNotificationList_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "notifications: ";
    if (v.notifications.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.notifications.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::kortex_driver::ActionNotification_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.notifications[i]);
    }
    if (v.notifications.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // KORTEX_DRIVER_MESSAGE_ACTIONNOTIFICATIONLIST_H
