// Generated by gencpp from file kortex_driver/Base_GpioConfiguration.msg
// DO NOT EDIT!


#ifndef KORTEX_DRIVER_MESSAGE_BASE_GPIOCONFIGURATION_H
#define KORTEX_DRIVER_MESSAGE_BASE_GPIOCONFIGURATION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <kortex_driver/GpioPinConfiguration.h>

namespace kortex_driver
{
template <class ContainerAllocator>
struct Base_GpioConfiguration_
{
  typedef Base_GpioConfiguration_<ContainerAllocator> Type;

  Base_GpioConfiguration_()
    : port_number(0)
    , pin_configurations()  {
    }
  Base_GpioConfiguration_(const ContainerAllocator& _alloc)
    : port_number(0)
    , pin_configurations(_alloc)  {
  (void)_alloc;
    }



   typedef uint32_t _port_number_type;
  _port_number_type port_number;

   typedef std::vector< ::kortex_driver::GpioPinConfiguration_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::kortex_driver::GpioPinConfiguration_<ContainerAllocator> >> _pin_configurations_type;
  _pin_configurations_type pin_configurations;





  typedef boost::shared_ptr< ::kortex_driver::Base_GpioConfiguration_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kortex_driver::Base_GpioConfiguration_<ContainerAllocator> const> ConstPtr;

}; // struct Base_GpioConfiguration_

typedef ::kortex_driver::Base_GpioConfiguration_<std::allocator<void> > Base_GpioConfiguration;

typedef boost::shared_ptr< ::kortex_driver::Base_GpioConfiguration > Base_GpioConfigurationPtr;
typedef boost::shared_ptr< ::kortex_driver::Base_GpioConfiguration const> Base_GpioConfigurationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kortex_driver::Base_GpioConfiguration_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kortex_driver::Base_GpioConfiguration_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kortex_driver::Base_GpioConfiguration_<ContainerAllocator1> & lhs, const ::kortex_driver::Base_GpioConfiguration_<ContainerAllocator2> & rhs)
{
  return lhs.port_number == rhs.port_number &&
    lhs.pin_configurations == rhs.pin_configurations;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kortex_driver::Base_GpioConfiguration_<ContainerAllocator1> & lhs, const ::kortex_driver::Base_GpioConfiguration_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kortex_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::kortex_driver::Base_GpioConfiguration_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kortex_driver::Base_GpioConfiguration_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kortex_driver::Base_GpioConfiguration_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kortex_driver::Base_GpioConfiguration_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kortex_driver::Base_GpioConfiguration_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kortex_driver::Base_GpioConfiguration_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kortex_driver::Base_GpioConfiguration_<ContainerAllocator> >
{
  static const char* value()
  {
    return "92f1de7cd4a1d8641179ab50f182b3f3";
  }

  static const char* value(const ::kortex_driver::Base_GpioConfiguration_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x92f1de7cd4a1d864ULL;
  static const uint64_t static_value2 = 0x1179ab50f182b3f3ULL;
};

template<class ContainerAllocator>
struct DataType< ::kortex_driver::Base_GpioConfiguration_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kortex_driver/Base_GpioConfiguration";
  }

  static const char* value(const ::kortex_driver::Base_GpioConfiguration_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kortex_driver::Base_GpioConfiguration_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"uint32 port_number\n"
"GpioPinConfiguration[] pin_configurations\n"
"================================================================================\n"
"MSG: kortex_driver/GpioPinConfiguration\n"
"\n"
"uint32 pin_id\n"
"uint32 pin_property\n"
"bool output_enable\n"
"bool default_output_value\n"
;
  }

  static const char* value(const ::kortex_driver::Base_GpioConfiguration_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kortex_driver::Base_GpioConfiguration_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.port_number);
      stream.next(m.pin_configurations);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Base_GpioConfiguration_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kortex_driver::Base_GpioConfiguration_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kortex_driver::Base_GpioConfiguration_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "port_number: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.port_number);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pin_configurations: ";
    if (v.pin_configurations.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.pin_configurations.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::kortex_driver::GpioPinConfiguration_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.pin_configurations[i]);
    }
    if (v.pin_configurations.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // KORTEX_DRIVER_MESSAGE_BASE_GPIOCONFIGURATION_H
