// Generated by gencpp from file kortex_driver/ComputeInverseKinematicsRequest.msg
// DO NOT EDIT!


#ifndef KORTEX_DRIVER_MESSAGE_COMPUTEINVERSEKINEMATICSREQUEST_H
#define KORTEX_DRIVER_MESSAGE_COMPUTEINVERSEKINEMATICSREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <kortex_driver/IKData.h>

namespace kortex_driver
{
template <class ContainerAllocator>
struct ComputeInverseKinematicsRequest_
{
  typedef ComputeInverseKinematicsRequest_<ContainerAllocator> Type;

  ComputeInverseKinematicsRequest_()
    : input()  {
    }
  ComputeInverseKinematicsRequest_(const ContainerAllocator& _alloc)
    : input(_alloc)  {
  (void)_alloc;
    }



   typedef  ::kortex_driver::IKData_<ContainerAllocator>  _input_type;
  _input_type input;





  typedef boost::shared_ptr< ::kortex_driver::ComputeInverseKinematicsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kortex_driver::ComputeInverseKinematicsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ComputeInverseKinematicsRequest_

typedef ::kortex_driver::ComputeInverseKinematicsRequest_<std::allocator<void> > ComputeInverseKinematicsRequest;

typedef boost::shared_ptr< ::kortex_driver::ComputeInverseKinematicsRequest > ComputeInverseKinematicsRequestPtr;
typedef boost::shared_ptr< ::kortex_driver::ComputeInverseKinematicsRequest const> ComputeInverseKinematicsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kortex_driver::ComputeInverseKinematicsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kortex_driver::ComputeInverseKinematicsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kortex_driver::ComputeInverseKinematicsRequest_<ContainerAllocator1> & lhs, const ::kortex_driver::ComputeInverseKinematicsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.input == rhs.input;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kortex_driver::ComputeInverseKinematicsRequest_<ContainerAllocator1> & lhs, const ::kortex_driver::ComputeInverseKinematicsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kortex_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::kortex_driver::ComputeInverseKinematicsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kortex_driver::ComputeInverseKinematicsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kortex_driver::ComputeInverseKinematicsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kortex_driver::ComputeInverseKinematicsRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kortex_driver::ComputeInverseKinematicsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kortex_driver::ComputeInverseKinematicsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kortex_driver::ComputeInverseKinematicsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6370dc05021b231d5d0b535bc12d00f3";
  }

  static const char* value(const ::kortex_driver::ComputeInverseKinematicsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6370dc05021b231dULL;
  static const uint64_t static_value2 = 0x5d0b535bc12d00f3ULL;
};

template<class ContainerAllocator>
struct DataType< ::kortex_driver::ComputeInverseKinematicsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kortex_driver/ComputeInverseKinematicsRequest";
  }

  static const char* value(const ::kortex_driver::ComputeInverseKinematicsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kortex_driver::ComputeInverseKinematicsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "IKData input\n"
"\n"
"================================================================================\n"
"MSG: kortex_driver/IKData\n"
"\n"
"Pose cartesian_pose\n"
"JointAngles guess\n"
"================================================================================\n"
"MSG: kortex_driver/Pose\n"
"\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
"float32 theta_x\n"
"float32 theta_y\n"
"float32 theta_z\n"
"================================================================================\n"
"MSG: kortex_driver/JointAngles\n"
"\n"
"JointAngle[] joint_angles\n"
"================================================================================\n"
"MSG: kortex_driver/JointAngle\n"
"\n"
"uint32 joint_identifier\n"
"float32 value\n"
;
  }

  static const char* value(const ::kortex_driver::ComputeInverseKinematicsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kortex_driver::ComputeInverseKinematicsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.input);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ComputeInverseKinematicsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kortex_driver::ComputeInverseKinematicsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kortex_driver::ComputeInverseKinematicsRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "input: ";
    Printer< ::kortex_driver::IKData_<ContainerAllocator> >::stream(s, indent + "  ", v.input);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KORTEX_DRIVER_MESSAGE_COMPUTEINVERSEKINEMATICSREQUEST_H
