// Generated by gencpp from file kortex_driver/FollowCartesianTrajectoryResult.msg
// DO NOT EDIT!


#ifndef KORTEX_DRIVER_MESSAGE_FOLLOWCARTESIANTRAJECTORYRESULT_H
#define KORTEX_DRIVER_MESSAGE_FOLLOWCARTESIANTRAJECTORYRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kortex_driver
{
template <class ContainerAllocator>
struct FollowCartesianTrajectoryResult_
{
  typedef FollowCartesianTrajectoryResult_<ContainerAllocator> Type;

  FollowCartesianTrajectoryResult_()
    : error_string()
    , error_code(0)  {
    }
  FollowCartesianTrajectoryResult_(const ContainerAllocator& _alloc)
    : error_string(_alloc)
    , error_code(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _error_string_type;
  _error_string_type error_string;

   typedef int32_t _error_code_type;
  _error_code_type error_code;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(SUCCESSFUL)
  #undef SUCCESSFUL
#endif
#if defined(_WIN32) && defined(INVALID_GOAL)
  #undef INVALID_GOAL
#endif
#if defined(_WIN32) && defined(PATH_TOLERANCE_VIOLATED)
  #undef PATH_TOLERANCE_VIOLATED
#endif

  enum {
    SUCCESSFUL = 0,
    INVALID_GOAL = -1,
    PATH_TOLERANCE_VIOLATED = -2,
  };


  typedef boost::shared_ptr< ::kortex_driver::FollowCartesianTrajectoryResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kortex_driver::FollowCartesianTrajectoryResult_<ContainerAllocator> const> ConstPtr;

}; // struct FollowCartesianTrajectoryResult_

typedef ::kortex_driver::FollowCartesianTrajectoryResult_<std::allocator<void> > FollowCartesianTrajectoryResult;

typedef boost::shared_ptr< ::kortex_driver::FollowCartesianTrajectoryResult > FollowCartesianTrajectoryResultPtr;
typedef boost::shared_ptr< ::kortex_driver::FollowCartesianTrajectoryResult const> FollowCartesianTrajectoryResultConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kortex_driver::FollowCartesianTrajectoryResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kortex_driver::FollowCartesianTrajectoryResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kortex_driver::FollowCartesianTrajectoryResult_<ContainerAllocator1> & lhs, const ::kortex_driver::FollowCartesianTrajectoryResult_<ContainerAllocator2> & rhs)
{
  return lhs.error_string == rhs.error_string &&
    lhs.error_code == rhs.error_code;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kortex_driver::FollowCartesianTrajectoryResult_<ContainerAllocator1> & lhs, const ::kortex_driver::FollowCartesianTrajectoryResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kortex_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::kortex_driver::FollowCartesianTrajectoryResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kortex_driver::FollowCartesianTrajectoryResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kortex_driver::FollowCartesianTrajectoryResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kortex_driver::FollowCartesianTrajectoryResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kortex_driver::FollowCartesianTrajectoryResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kortex_driver::FollowCartesianTrajectoryResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kortex_driver::FollowCartesianTrajectoryResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e845eb53c49e5687cc804e4383078872";
  }

  static const char* value(const ::kortex_driver::FollowCartesianTrajectoryResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe845eb53c49e5687ULL;
  static const uint64_t static_value2 = 0xcc804e4383078872ULL;
};

template<class ContainerAllocator>
struct DataType< ::kortex_driver::FollowCartesianTrajectoryResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kortex_driver/FollowCartesianTrajectoryResult";
  }

  static const char* value(const ::kortex_driver::FollowCartesianTrajectoryResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kortex_driver::FollowCartesianTrajectoryResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#result definition\n"
"string error_string\n"
"int32 error_code\n"
"int32 SUCCESSFUL = 0\n"
"int32 INVALID_GOAL = -1\n"
"int32 PATH_TOLERANCE_VIOLATED = -2\n"
"\n"
;
  }

  static const char* value(const ::kortex_driver::FollowCartesianTrajectoryResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kortex_driver::FollowCartesianTrajectoryResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.error_string);
      stream.next(m.error_code);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FollowCartesianTrajectoryResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kortex_driver::FollowCartesianTrajectoryResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kortex_driver::FollowCartesianTrajectoryResult_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "error_string: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.error_string);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "error_code: ";
    Printer<int32_t>::stream(s, indent + "  ", v.error_code);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KORTEX_DRIVER_MESSAGE_FOLLOWCARTESIANTRAJECTORYRESULT_H
