// Generated by gencpp from file kortex_driver/GetBluetoothEnableState.msg
// DO NOT EDIT!


#ifndef KORTEX_DRIVER_MESSAGE_GETBLUETOOTHENABLESTATE_H
#define KORTEX_DRIVER_MESSAGE_GETBLUETOOTHENABLESTATE_H

#include <ros/service_traits.h>


#include <kortex_driver/GetBluetoothEnableStateRequest.h>
#include <kortex_driver/GetBluetoothEnableStateResponse.h>


namespace kortex_driver
{

struct GetBluetoothEnableState
{

typedef GetBluetoothEnableStateRequest Request;
typedef GetBluetoothEnableStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetBluetoothEnableState
} // namespace kortex_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kortex_driver::GetBluetoothEnableState > {
  static const char* value()
  {
    return "9747040002a13b23ba7503e4b2f380fb";
  }

  static const char* value(const ::kortex_driver::GetBluetoothEnableState&) { return value(); }
};

template<>
struct DataType< ::kortex_driver::GetBluetoothEnableState > {
  static const char* value()
  {
    return "kortex_driver/GetBluetoothEnableState";
  }

  static const char* value(const ::kortex_driver::GetBluetoothEnableState&) { return value(); }
};


// service_traits::MD5Sum< ::kortex_driver::GetBluetoothEnableStateRequest> should match
// service_traits::MD5Sum< ::kortex_driver::GetBluetoothEnableState >
template<>
struct MD5Sum< ::kortex_driver::GetBluetoothEnableStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kortex_driver::GetBluetoothEnableState >::value();
  }
  static const char* value(const ::kortex_driver::GetBluetoothEnableStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kortex_driver::GetBluetoothEnableStateRequest> should match
// service_traits::DataType< ::kortex_driver::GetBluetoothEnableState >
template<>
struct DataType< ::kortex_driver::GetBluetoothEnableStateRequest>
{
  static const char* value()
  {
    return DataType< ::kortex_driver::GetBluetoothEnableState >::value();
  }
  static const char* value(const ::kortex_driver::GetBluetoothEnableStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kortex_driver::GetBluetoothEnableStateResponse> should match
// service_traits::MD5Sum< ::kortex_driver::GetBluetoothEnableState >
template<>
struct MD5Sum< ::kortex_driver::GetBluetoothEnableStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kortex_driver::GetBluetoothEnableState >::value();
  }
  static const char* value(const ::kortex_driver::GetBluetoothEnableStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kortex_driver::GetBluetoothEnableStateResponse> should match
// service_traits::DataType< ::kortex_driver::GetBluetoothEnableState >
template<>
struct DataType< ::kortex_driver::GetBluetoothEnableStateResponse>
{
  static const char* value()
  {
    return DataType< ::kortex_driver::GetBluetoothEnableState >::value();
  }
  static const char* value(const ::kortex_driver::GetBluetoothEnableStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KORTEX_DRIVER_MESSAGE_GETBLUETOOTHENABLESTATE_H
