// Generated by gencpp from file kortex_driver/GpioCommand.msg
// DO NOT EDIT!


#ifndef KORTEX_DRIVER_MESSAGE_GPIOCOMMAND_H
#define KORTEX_DRIVER_MESSAGE_GPIOCOMMAND_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kortex_driver
{
template <class ContainerAllocator>
struct GpioCommand_
{
  typedef GpioCommand_<ContainerAllocator> Type;

  GpioCommand_()
    : port_identifier(0)
    , pin_identifier(0)
    , action(0)
    , period(0)  {
    }
  GpioCommand_(const ContainerAllocator& _alloc)
    : port_identifier(0)
    , pin_identifier(0)
    , action(0)
    , period(0)  {
  (void)_alloc;
    }



   typedef uint32_t _port_identifier_type;
  _port_identifier_type port_identifier;

   typedef uint32_t _pin_identifier_type;
  _pin_identifier_type pin_identifier;

   typedef uint32_t _action_type;
  _action_type action;

   typedef uint32_t _period_type;
  _period_type period;





  typedef boost::shared_ptr< ::kortex_driver::GpioCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kortex_driver::GpioCommand_<ContainerAllocator> const> ConstPtr;

}; // struct GpioCommand_

typedef ::kortex_driver::GpioCommand_<std::allocator<void> > GpioCommand;

typedef boost::shared_ptr< ::kortex_driver::GpioCommand > GpioCommandPtr;
typedef boost::shared_ptr< ::kortex_driver::GpioCommand const> GpioCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kortex_driver::GpioCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kortex_driver::GpioCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kortex_driver::GpioCommand_<ContainerAllocator1> & lhs, const ::kortex_driver::GpioCommand_<ContainerAllocator2> & rhs)
{
  return lhs.port_identifier == rhs.port_identifier &&
    lhs.pin_identifier == rhs.pin_identifier &&
    lhs.action == rhs.action &&
    lhs.period == rhs.period;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kortex_driver::GpioCommand_<ContainerAllocator1> & lhs, const ::kortex_driver::GpioCommand_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kortex_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::kortex_driver::GpioCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kortex_driver::GpioCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kortex_driver::GpioCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kortex_driver::GpioCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kortex_driver::GpioCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kortex_driver::GpioCommand_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kortex_driver::GpioCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "407fd312655ca86f1a6125a8f767d374";
  }

  static const char* value(const ::kortex_driver::GpioCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x407fd312655ca86fULL;
  static const uint64_t static_value2 = 0x1a6125a8f767d374ULL;
};

template<class ContainerAllocator>
struct DataType< ::kortex_driver::GpioCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kortex_driver/GpioCommand";
  }

  static const char* value(const ::kortex_driver::GpioCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kortex_driver::GpioCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"uint32 port_identifier\n"
"uint32 pin_identifier\n"
"uint32 action\n"
"uint32 period\n"
;
  }

  static const char* value(const ::kortex_driver::GpioCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kortex_driver::GpioCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.port_identifier);
      stream.next(m.pin_identifier);
      stream.next(m.action);
      stream.next(m.period);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GpioCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kortex_driver::GpioCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kortex_driver::GpioCommand_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "port_identifier: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.port_identifier);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pin_identifier: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.pin_identifier);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "action: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.action);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "period: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.period);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KORTEX_DRIVER_MESSAGE_GPIOCOMMAND_H
