// Generated by gencpp from file kortex_driver/RFConfiguration.msg
// DO NOT EDIT!


#ifndef KORTEX_DRIVER_MESSAGE_RFCONFIGURATION_H
#define KORTEX_DRIVER_MESSAGE_RFCONFIGURATION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <kortex_driver/WifiEnableState.h>
#include <kortex_driver/BluetoothEnableState.h>

namespace kortex_driver
{
template <class ContainerAllocator>
struct RFConfiguration_
{
  typedef RFConfiguration_<ContainerAllocator> Type;

  RFConfiguration_()
    : wifi_enable_state()
    , bluetooth_enable_state()  {
    }
  RFConfiguration_(const ContainerAllocator& _alloc)
    : wifi_enable_state(_alloc)
    , bluetooth_enable_state(_alloc)  {
  (void)_alloc;
    }



   typedef  ::kortex_driver::WifiEnableState_<ContainerAllocator>  _wifi_enable_state_type;
  _wifi_enable_state_type wifi_enable_state;

   typedef  ::kortex_driver::BluetoothEnableState_<ContainerAllocator>  _bluetooth_enable_state_type;
  _bluetooth_enable_state_type bluetooth_enable_state;





  typedef boost::shared_ptr< ::kortex_driver::RFConfiguration_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kortex_driver::RFConfiguration_<ContainerAllocator> const> ConstPtr;

}; // struct RFConfiguration_

typedef ::kortex_driver::RFConfiguration_<std::allocator<void> > RFConfiguration;

typedef boost::shared_ptr< ::kortex_driver::RFConfiguration > RFConfigurationPtr;
typedef boost::shared_ptr< ::kortex_driver::RFConfiguration const> RFConfigurationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kortex_driver::RFConfiguration_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kortex_driver::RFConfiguration_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kortex_driver::RFConfiguration_<ContainerAllocator1> & lhs, const ::kortex_driver::RFConfiguration_<ContainerAllocator2> & rhs)
{
  return lhs.wifi_enable_state == rhs.wifi_enable_state &&
    lhs.bluetooth_enable_state == rhs.bluetooth_enable_state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kortex_driver::RFConfiguration_<ContainerAllocator1> & lhs, const ::kortex_driver::RFConfiguration_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kortex_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::kortex_driver::RFConfiguration_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kortex_driver::RFConfiguration_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kortex_driver::RFConfiguration_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kortex_driver::RFConfiguration_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kortex_driver::RFConfiguration_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kortex_driver::RFConfiguration_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kortex_driver::RFConfiguration_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b8bfe540c76a207913f7638bb2dbbae6";
  }

  static const char* value(const ::kortex_driver::RFConfiguration_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb8bfe540c76a2079ULL;
  static const uint64_t static_value2 = 0x13f7638bb2dbbae6ULL;
};

template<class ContainerAllocator>
struct DataType< ::kortex_driver::RFConfiguration_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kortex_driver/RFConfiguration";
  }

  static const char* value(const ::kortex_driver::RFConfiguration_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kortex_driver::RFConfiguration_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"WifiEnableState wifi_enable_state\n"
"BluetoothEnableState bluetooth_enable_state\n"
"================================================================================\n"
"MSG: kortex_driver/WifiEnableState\n"
"\n"
"bool enabled\n"
"================================================================================\n"
"MSG: kortex_driver/BluetoothEnableState\n"
"\n"
"bool enabled\n"
;
  }

  static const char* value(const ::kortex_driver::RFConfiguration_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kortex_driver::RFConfiguration_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.wifi_enable_state);
      stream.next(m.bluetooth_enable_state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RFConfiguration_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kortex_driver::RFConfiguration_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kortex_driver::RFConfiguration_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "wifi_enable_state: ";
    Printer< ::kortex_driver::WifiEnableState_<ContainerAllocator> >::stream(s, indent + "  ", v.wifi_enable_state);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "bluetooth_enable_state: ";
    Printer< ::kortex_driver::BluetoothEnableState_<ContainerAllocator> >::stream(s, indent + "  ", v.bluetooth_enable_state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KORTEX_DRIVER_MESSAGE_RFCONFIGURATION_H
