// Generated by gencpp from file kortex_driver/SetBluetoothEnableStateRequest.msg
// DO NOT EDIT!


#ifndef KORTEX_DRIVER_MESSAGE_SETBLUETOOTHENABLESTATEREQUEST_H
#define KORTEX_DRIVER_MESSAGE_SETBLUETOOTHENABLESTATEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <kortex_driver/BluetoothEnableState.h>

namespace kortex_driver
{
template <class ContainerAllocator>
struct SetBluetoothEnableStateRequest_
{
  typedef SetBluetoothEnableStateRequest_<ContainerAllocator> Type;

  SetBluetoothEnableStateRequest_()
    : input()  {
    }
  SetBluetoothEnableStateRequest_(const ContainerAllocator& _alloc)
    : input(_alloc)  {
  (void)_alloc;
    }



   typedef  ::kortex_driver::BluetoothEnableState_<ContainerAllocator>  _input_type;
  _input_type input;





  typedef boost::shared_ptr< ::kortex_driver::SetBluetoothEnableStateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kortex_driver::SetBluetoothEnableStateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetBluetoothEnableStateRequest_

typedef ::kortex_driver::SetBluetoothEnableStateRequest_<std::allocator<void> > SetBluetoothEnableStateRequest;

typedef boost::shared_ptr< ::kortex_driver::SetBluetoothEnableStateRequest > SetBluetoothEnableStateRequestPtr;
typedef boost::shared_ptr< ::kortex_driver::SetBluetoothEnableStateRequest const> SetBluetoothEnableStateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kortex_driver::SetBluetoothEnableStateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kortex_driver::SetBluetoothEnableStateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kortex_driver::SetBluetoothEnableStateRequest_<ContainerAllocator1> & lhs, const ::kortex_driver::SetBluetoothEnableStateRequest_<ContainerAllocator2> & rhs)
{
  return lhs.input == rhs.input;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kortex_driver::SetBluetoothEnableStateRequest_<ContainerAllocator1> & lhs, const ::kortex_driver::SetBluetoothEnableStateRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kortex_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::kortex_driver::SetBluetoothEnableStateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kortex_driver::SetBluetoothEnableStateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kortex_driver::SetBluetoothEnableStateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kortex_driver::SetBluetoothEnableStateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kortex_driver::SetBluetoothEnableStateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kortex_driver::SetBluetoothEnableStateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kortex_driver::SetBluetoothEnableStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d5db8254e8ad9ee9141adf349015e9ec";
  }

  static const char* value(const ::kortex_driver::SetBluetoothEnableStateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd5db8254e8ad9ee9ULL;
  static const uint64_t static_value2 = 0x141adf349015e9ecULL;
};

template<class ContainerAllocator>
struct DataType< ::kortex_driver::SetBluetoothEnableStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kortex_driver/SetBluetoothEnableStateRequest";
  }

  static const char* value(const ::kortex_driver::SetBluetoothEnableStateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kortex_driver::SetBluetoothEnableStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "BluetoothEnableState input\n"
"\n"
"================================================================================\n"
"MSG: kortex_driver/BluetoothEnableState\n"
"\n"
"bool enabled\n"
;
  }

  static const char* value(const ::kortex_driver::SetBluetoothEnableStateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kortex_driver::SetBluetoothEnableStateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.input);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetBluetoothEnableStateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kortex_driver::SetBluetoothEnableStateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kortex_driver::SetBluetoothEnableStateRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "input: ";
    Printer< ::kortex_driver::BluetoothEnableState_<ContainerAllocator> >::stream(s, indent + "  ", v.input);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KORTEX_DRIVER_MESSAGE_SETBLUETOOTHENABLESTATEREQUEST_H
