// Generated by gencpp from file kortex_driver/WaypointList.msg
// DO NOT EDIT!


#ifndef KORTEX_DRIVER_MESSAGE_WAYPOINTLIST_H
#define KORTEX_DRIVER_MESSAGE_WAYPOINTLIST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <kortex_driver/Waypoint.h>

namespace kortex_driver
{
template <class ContainerAllocator>
struct WaypointList_
{
  typedef WaypointList_<ContainerAllocator> Type;

  WaypointList_()
    : waypoints()
    , duration(0.0)
    , use_optimal_blending(false)  {
    }
  WaypointList_(const ContainerAllocator& _alloc)
    : waypoints(_alloc)
    , duration(0.0)
    , use_optimal_blending(false)  {
  (void)_alloc;
    }



   typedef std::vector< ::kortex_driver::Waypoint_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::kortex_driver::Waypoint_<ContainerAllocator> >> _waypoints_type;
  _waypoints_type waypoints;

   typedef float _duration_type;
  _duration_type duration;

   typedef uint8_t _use_optimal_blending_type;
  _use_optimal_blending_type use_optimal_blending;





  typedef boost::shared_ptr< ::kortex_driver::WaypointList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kortex_driver::WaypointList_<ContainerAllocator> const> ConstPtr;

}; // struct WaypointList_

typedef ::kortex_driver::WaypointList_<std::allocator<void> > WaypointList;

typedef boost::shared_ptr< ::kortex_driver::WaypointList > WaypointListPtr;
typedef boost::shared_ptr< ::kortex_driver::WaypointList const> WaypointListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kortex_driver::WaypointList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kortex_driver::WaypointList_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kortex_driver::WaypointList_<ContainerAllocator1> & lhs, const ::kortex_driver::WaypointList_<ContainerAllocator2> & rhs)
{
  return lhs.waypoints == rhs.waypoints &&
    lhs.duration == rhs.duration &&
    lhs.use_optimal_blending == rhs.use_optimal_blending;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kortex_driver::WaypointList_<ContainerAllocator1> & lhs, const ::kortex_driver::WaypointList_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kortex_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::kortex_driver::WaypointList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kortex_driver::WaypointList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kortex_driver::WaypointList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kortex_driver::WaypointList_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kortex_driver::WaypointList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kortex_driver::WaypointList_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kortex_driver::WaypointList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7b5e341798f530d68dce10b5bad29aad";
  }

  static const char* value(const ::kortex_driver::WaypointList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7b5e341798f530d6ULL;
  static const uint64_t static_value2 = 0x8dce10b5bad29aadULL;
};

template<class ContainerAllocator>
struct DataType< ::kortex_driver::WaypointList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kortex_driver/WaypointList";
  }

  static const char* value(const ::kortex_driver::WaypointList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kortex_driver::WaypointList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"Waypoint[] waypoints\n"
"float32 duration\n"
"bool use_optimal_blending\n"
"================================================================================\n"
"MSG: kortex_driver/Waypoint\n"
"\n"
"string name\n"
"Waypoint_type_of_waypoint oneof_type_of_waypoint\n"
"================================================================================\n"
"MSG: kortex_driver/Waypoint_type_of_waypoint\n"
"\n"
"AngularWaypoint[] angular_waypoint\n"
"CartesianWaypoint[] cartesian_waypoint\n"
"================================================================================\n"
"MSG: kortex_driver/AngularWaypoint\n"
"\n"
"float32[] angles\n"
"float32[] maximum_velocities\n"
"float32 duration\n"
"================================================================================\n"
"MSG: kortex_driver/CartesianWaypoint\n"
"\n"
"Pose pose\n"
"uint32 reference_frame\n"
"float32 maximum_linear_velocity\n"
"float32 maximum_angular_velocity\n"
"float32 blending_radius\n"
"================================================================================\n"
"MSG: kortex_driver/Pose\n"
"\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
"float32 theta_x\n"
"float32 theta_y\n"
"float32 theta_z\n"
;
  }

  static const char* value(const ::kortex_driver::WaypointList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kortex_driver::WaypointList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.waypoints);
      stream.next(m.duration);
      stream.next(m.use_optimal_blending);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WaypointList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kortex_driver::WaypointList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kortex_driver::WaypointList_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "waypoints: ";
    if (v.waypoints.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.waypoints.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::kortex_driver::Waypoint_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.waypoints[i]);
    }
    if (v.waypoints.empty() || false)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "duration: ";
    Printer<float>::stream(s, indent + "  ", v.duration);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "use_optimal_blending: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.use_optimal_blending);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KORTEX_DRIVER_MESSAGE_WAYPOINTLIST_H
